### ISSUE TITLE
Script to test search features in production

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#606] opened 2018-04-20 20:21 UTC
Write a script to test some of our major search features in production.

This is a script that you run locally in your laptop, that does searches on the real https://hypothes.is and verifies that the results are correct. It can run some searches with and without the [Elasticsearch 6.2 feature flag](https://github.com/hypothesis/product-backlog/issues/601) and verify that the results are the same.

* The script should probably mostly work by calling the API: <http://h.readthedocs.io/en/latest/api/>
* Click around in the client and on activity pages and see what different kinds of searches they do, in order to discover what are the main search features that should be tested

**Comment by judell** [comment] 2018-05-01 16:14
> Click around in the client and on activity pages and see what different kinds of searches they do

Maybe also dig /api/search queries out of (a sample of) our raw access logs and summarize them? If that's of interest, and someone can get me a log sample, I'd be happy to volunteer for that. 

Update: I just realized that although some queries come by way of /api/search and will be in the nginx access log, most come from activity pages which calls the search client directly, I think. Is ES search history available somewhere?

**Comment by robertknight** [comment] 2018-07-24 10:47
There is a facility in h that will probably be helpful for testing this via the API: Any feature flag can be enabled for a request by adding a `__feature__[<flag name>]`  query parameter with a non-empty value. For example https://hypothes.is/api/search?uri=http://example.org&__feature__[search_es6]=1.

**Comment by robertknight** [comment] 2018-07-26 16:38
It turns out that the above suggestion (using `__feature__[<flag name>]` query params) is not possible at the moment because of the way that the search API processes query params - anything unknown gets forwarded to Elasticsearch directly as an "indexed document must contain this term in this field" condition!

TBQH I think the risk of a divergence in behaviour between ES1 and ES6 in production is relatively unlikely - it is well tested software, we have tests for all of the functionality that we use and we're only really using quite basic features of the service.

We'll keep an eye out for any errors or unexpected behaviour in production over the next few days.

**Comment by robertknight** [comment] 2018-07-30 14:04
I'm going to close this for now on the basis I think we have done a sufficient amount of testing/verification via automated (tests) + manual (poking at things in production) means. I do think we should fix the issue that prevents usage of feature flag query params in `/api/search` requests though. This is tracked on the sprint board.

**Closed as completed by robertknight** 2018-07-30 14:04 UTC
