### ISSUE TITLE
Spike - LTI 1.3

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1226] opened 2021-08-22 00:54 UTC
Filling this out in the morning. Sorry.

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

### Add tags - did you add labels? 
If this a customer requested feature, make sure to add that label.

**Comment by chrisshaw** [comment] 2022-02-02 08:17
Duplicate of https://github.com/hypothesis/lms/issues/877

**Closed as completed by chrisshaw** 2022-02-02 08:17 UTC
Labels: lms
