### ISSUE TITLE
Client closes when I try to click in for a second time

### ISSUE THREAD

**Issue by heatherstaines** [hypothesis/product-backlog#719] opened 2018-07-21 11:30 UTC
### Steps to reproduce
1. Annotating on Firefox 61.0.1 
2. This url: https://www.smithsonianmag.com/history/buried-ash-vesuvius-scrolls-are-being-read-new-xray-technique-180969358/
3. No problem with highlights, but if I try to create an annotation, I can--but as soon as I leave the actual annotation card (either to try to make a tag or to post) the next click closes the sidebar. I also cannot get back into the card itself.

### Expected behaviour
Tell us what should happen.
I should be able to complete the post or make a tag.

### Actual behaviour
Tell us what happens instead.
Sidebar closes.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue. Firefox 61.0.1 

### Add tags - did you add labels? 
If this a customer requested feature, make sure to add that label.

**Comment by heatherstaines** [comment] 2018-07-21 11:32
Actually, this seems to be working now, so please delete.

**Comment by heatherstaines** [comment] 2018-07-21 11:38
Okay, now it's not working... Sigh.

**Comment by klemay** [comment] 2018-08-01 15:11
I tried this in Firefox 61.0.1 and was not able to reproduce - closing this issue.

**Closed as completed by klemay** 2018-08-01 15:11 UTC
