### ISSUE TITLE
Annotation does not work properly in OpenStax textbook SPA

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#493] opened 2018-02-22 20:04 UTC
_(Edit from robertknight: See https://github.com/hypothesis/product-backlog/issues/493#issuecomment-367923295 for explanation of issue and https://github.com/hypothesis/client/issues/142 for main issue for this problem)_

Honestly not sure whether this is a bug or feature at this point. Happy to recategorize if necessary.
This comes from a Zendesk ticket: https://hypothesis.zendesk.com/agent/tickets/2239
And is possibly related to this one: https://hypothesis.zendesk.com/agent/tickets/2184

### Steps to reproduce
1. Join this group:  https://hypothes.is/groups/di3rZLja/astronomy-spring-18 (note: no need to join the group - this happens in the Public channel as well)
2. Annotate this online textbook: https://cnx.org/contents/LnN76Opl@13.132:_45u6IpQ@4/Introduction
3. Navigate to a different page, and make more annotations. 

### Expected behaviour
The Hypothesis sidebar refreshes when the new page loads. You see annotations made on that page. When you navigate back to the first page, you see the annotation you made in step 2.

### Actual behaviour
The Hypothesis sidebar does not refresh, and you still see the annotation you made in Step 2. Refreshing your browser page seems to fix this, but what really happens is it causes your annotations to become orphans. 

### Browser/system information
Chrome v 64.0.3282.167 for Mac OS, but is happening for this faculty member and all his students, so I don't think this is browser-specific. 

### Additional details
I *think* this might be happening because Hypothesis somehow doesn't see these textbook chapters as distinct pages. When you navigate through the textbook, it's almost as if H thinks the page content is changing instead of realizing the user is navigating to a different page.

**Comment by klemay** [comment] 2018-02-22 20:10
One thing to add: I did notice that all the text book pages contain ```<link rel="canonical" href="//cnx.org/contents/2e737be8-ea65-48c3-aa0a-9f35b4c6a966/">``` - is this the cause of the issue? If so, does the publisher need to remove these ```<links>```s, or is there a way around this?

**Comment by judell** [comment] 2018-02-22 20:21
The problem is that the target pages are in an iframe.

> all the text book pages contain &lt;link rel="canonical" href="//cnx.org/contents/2e737be8-ea65-48c3-aa0a-9f35b4c6a966/"> 

The containing page has that, but not the contained pages, so that's OK.

The solution here is to invite the client into the contained iframes using the enable-annotation attribute on the iframe. 

http://h.readthedocs.io/projects/client/en/latest/publishers/embedding/#enabling-annotation-of-iframed-content

**Comment by klemay** [comment] 2018-02-22 20:25
This is where it gets tricky though - the user who reported this issue has no control over the code for this page. I could see this happening a lot with teachers and online textbooks.

**Comment by judell** [comment] 2018-02-22 20:28
The user has no control, but the platform does, and it is OpenStax, we know them, I think they'll be on board with making that change. I'll send you contact info out of band.

**Comment by klemay** [comment] 2018-02-22 20:37
Changed this to a feature request. Will need to do some thinking about how to handle similar issues in the future. It is great that the publisher is a friend of ours in this case, but that might not always happen! Thanks Jon!

**Comment by robertknight** [comment] 2018-02-23 06:35
@judell there are no iframes on this particular OpenStax text book. The problem is what @klemay observed here:

> I think this might be happening because Hypothesis somehow doesn't see these textbook chapters as distinct pages. When you navigate through the textbook, it's almost as if H thinks the page content is changing instead of realizing the user is navigating to a different page.

The the textbook is a single page application, ie. when you click "Next" the page _stays the same_ but the app fetches some new content using JavaScript and updates the URL using the History API.  This issue also affects sites such as GitHub and Medium which use a technique called PJAX to make switching pages faster.

I usually know whether a site uses PJAX or is a single page application "by feel", but if you are not sure you can tell by:

1. Opening the Chrome Developer Tools and switching to the Network tab
2. Selecting the "Doc" filter (short for "HTML documents")
3. Clicking links on the page (eg. the "Next" links in this case) and seeing whether new HTML documents are fetched or not. In a "normal" web page, each link you click will fetch a new HTML page. In a site like this, note that no new entries appear in the network list as you navigate around, because the browser is not actually fetching new pages.

<img width="1081" alt="screenshot 2018-02-23 06 29 19" src="https://user-images.githubusercontent.com/2458/36581191-a9eba88e-1863-11e8-9517-eac8890f62a9.png">

The main GitHub issue for this is https://github.com/hypothesis/client/issues/142 . I think it is worth keeping this issue around, or at least the issue description from it, because it is a nice test case for any fix.

**Comment by judell** [comment] 2018-02-23 07:50
> there are no iframes on this particular OpenStax text book

Indeed there are not! I must have opened the debugger in the wrong tab, sorry!

And by the way, if it were an outer/inner frame situation, @katelyn, it would probably be best for them to embed the client in the inner frame, because of an issue we discovered when investigating how to embed the client at, e.g., https://osf.io/bgyd5/. @robertknight's off-GitHub description of that issue:

> _I've realized there is a fundamental issue in `src/sidebar/frame-sync.js` around handling of multiple frames which is actually not specific to this scenario. In brief, all connected frames will try to anchor all annotations fetched from the API. Depending on what order anchoring results from the correct vs. wrong frames for a particular annotation come back, the annotation will show up as an orphan or not._

I'm not sure if that's been filed, actually. If not I can, though @robertknight has the clearest view of it. And perhaps http://h.readthedocs.io/projects/client/en/latest/publishers/embedding/?highlight=enable-annotation should mention it.

**Comment by klemay** [comment] 2018-03-01 19:46
Another example: https://quod.lib.umich.edu/d/dh/13474172.0001.001/1:3/--ethical-programs-hospitality-and-the-rhetorics-of-software?g=dculture;rgn=div1;view=fulltext;xc=1

**Comment by klemay** [comment] 2018-03-23 14:41
Another user request: https://hypothesis.zendesk.com/agent/tickets/2334

**Comment by klemay** [comment] 2018-03-28 14:50
Another user request: https://hypothesis.zendesk.com/agent/tickets/2345

**Comment by klemay** [comment] 2018-03-29 19:38
Another user request: https://hypothesis.zendesk.com/agent/tickets/2357

**Comment by klemay** [comment] 2018-03-29 19:41
Also linking relevant issue from client repository: https://github.com/hypothesis/client/issues/142

**Comment by ajpeddakotla** [comment] 2018-09-05 17:28
| Business Viability | User Engagement | Building Community | Level of Effort |
|---|---|---|---|
| 3 | 3 | 3 | 3 |

**Comment by klemay** [comment] 2018-09-11 15:52
another example: https://hypothesis.zendesk.com/agent/tickets/3032

**Comment by klemay** [comment] 2018-09-17 17:52
Another SPA example: https://dashboard.wikiedu.org/training/students/wikipedia-essentials/policies-and-guidelines-basic-overview

**Comment by ajpeddakotla** [comment] 2018-09-24 20:28
Another SPA example: https://hypothesis.zendesk.com/agent/tickets/3109

**Comment by klemay** [comment] 2018-10-01 16:41
Another example: https://hypothesis.zendesk.com/agent/tickets/3145

I think it's interesting/important to note that in this case, the user was afraid that their private annotations might be shown to other people. Her thinking: if annotations for the wrong page are being shown, is it possible annotations for the wrong USER might be shown? We know the answer is no, but for someone who is not as familiar with H as we are, I think that's a fair thing to worry about.

**Comment by klemay** [comment] 2018-10-11 20:25
Another example: http://journal.media-culture.org.au/index.php/mcjournal/

**Comment by klemay** [comment] 2018-10-31 15:23
Another example: https://hypothesis.zendesk.com/agent/tickets/3278

**Comment by klemay** [comment] 2018-10-31 17:13
Another example: https://github.com/hypothesis/h/issues/5401

**Comment by judell** [comment] 2020-04-08 19:51
OpenStax have implemented their own highlighter. And because their page evidently swallows the selection event, the Hypothesis client can no longer even attempt to annotate an OpenStax book.

**Comment by phoenixeliot** [comment] 2021-11-15 22:51
Just adding a note that Youtube has this problem quite severely — almost all youtube annotations I create are associated with the wrong youtube URL. I'm not sure exactly the pattern, but it's always a different earlier youtube page I had open, sometimes even from a different tab.

**Comment by mraxilus** [comment] 2021-11-16 10:09
> 
> 
> Just adding a note that Youtube has this problem quite severely — almost all youtube annotations I create are associated with the wrong youtube URL. I'm not sure exactly the pattern, but it's always a different earlier youtube page I had open, sometimes even from a different tab.

As a temporary workaround, I've found that it disambiguates the pages better if you open every video in a new tab; and refresh for good measure. I think it has something to do with YouTube pages dynamically updating pages rather than loading a whole new page.

You can still get the merging highlights issue, but a lot less frequently.

**Comment by robertknight** [comment] 2021-11-16 10:41
> I think it has something to do with YouTube pages dynamically updating pages rather than loading a whole new page.

Yes, this is the problem. The client does use the current URL (as shown in the browser) and metadata (embedded in the page) whenever you create an annotation. However it does not currently refresh annotations when you navigate around a website which does client-side navigation (ie. changing the URL and content using JavaScript rather than loading an entire new HTML page from the server). Additionally if the website does not properly update embedded metadata in the page after a client-side navigation, this can cause annotations to have metadata attached to them which reflects the original page on which you landed.

**Closed as completed** 2022-07-13 20:48 UTC
Labels: feature request, user requested, browser-extension, education
