### ISSUE TITLE
How can we enable deleting user accounts that have created a group that has annotations from other users?

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#815] opened 2018-09-25 17:15 UTC
Spike to decide how can we enable deleting user account that have created a group that has annotations from other users.

Possibilities:

* Delete the groups and any annotations they contain
* Reassign the group creator to another user (possibly a default "Ghost User" account), thus enabling the original group creator user to be deleted

Related:

* https://github.com/hypothesis/private-issues/issues/14
* https://github.com/hypothesis/product-backlog/issues/798

**Comment by hmstepanek** [comment] 2018-10-12 16:15
I think it would make sense to re-assign the creator role to the user who has annotated the most in that group (that haven't been moderated).

**Comment by lyzadanger** [comment] 2018-10-12 16:30
@hmstepanek I think it could be useful to list out the various possible behaviors and perhaps discuss pros and cons? (Your proposed direction may still be where we end up, but I think it could be useful to be explicit about which options we thought of and considered).

**Comment by hmstepanek** [comment] 2018-10-12 17:19
Yeah I definitely will! Doing some digging now to see what all we have to do to enable this.

**Comment by hmstepanek** [comment] 2018-10-12 23:39
Another option is to do this but rather than automatically select a new creator, enable an admin to set the creator to a new user manually via the edit group page (obviously this would have to be enabled for private groups) and then go back and delete the user who is no longer the creator of that group. This also potentially has the advantage that the user who is deleting the account can select a new user to run the group.

**Comment by hmstepanek** [comment] 2018-10-15 16:13
It looks like enabling the group edit page for private groups is pretty simple:
 1. Remove the if else so you can click on the group name to take you to the private group edit page.
 1. Only display the org if there is an org associated with the group.
 1. Add private as a group type.
 1. Remove the requirement that the scope must be specified for private groups.

From there we can assign a new creator to the group.

**Comment by hmstepanek** [comment] 2018-10-15 18:10
Options:

- Reassign all annotations to be "Only Me" in the Public group. 
   This is probably the safest/easiest thing to do as we don't have to add any functionality. But it means members can't see each others annotations.
- Reassign the group creator to a "ghost user account".
   This would require some sort of "ghost user account" to exist like the Public group already exists.
The only potential problem I see with this is there is now no one to moderate the group. 
-  Reassign the group creator as None.
   This is the easiest thing to do and AFAICT doesn't result in any unexpected behavior. The only potential problem I see with this is there is now no one to moderate the group. 
- Reassign the group creator to another user of the group manually via the admin page.
   This would require enabling private groups on the edit page and manual input from an admin at H to decide who the new creator will be.
- Reassign the group creator to the most active user of the group automatically when deleting the creator of a group.
   This would require adding logic to run a very non-performant db query to get the new user and then re-assign them as the creator.

**Comment by hmstepanek** [comment] 2018-10-15 18:27
@klemay @ajpeddakotla I think this is at a point where I could use some feedback from you two.

**Comment by jeremydean** [comment] 2018-10-15 20:03
I don't think (1) above is good since it would mean the remaining group members wouldn't be able to see each other's annotations, right?

**Comment by klemay** [comment] 2018-10-15 22:24
For all of the options above, I have a potentially complicating question: what happens if there are replies to the deleted user's top-level annotations? I.e., I create a group and Hannah replies to some of my annotations, and then I delete my account. Do Hannah's annotations get promoted to top-level? Do we implement some sort of [annotation deleted] notice? 

I feel like we may want to offer a choice: promote another user to creator role, or simply delete everything. 

I would be interested to know what @dwolfe thinks from a user perspective here. What do users expect to happen if they create a group and later delete their account?

**Comment by hmstepanek** [comment] 2018-10-15 22:38
@jeremydean That's correct.

**Comment by hmstepanek** [comment] 2018-10-15 22:43
@klemay Our current implementation appears to simply delete the user's annotations and leave the replies untouched. So...while the replies would still be in the db and elasticsearch, they would not show up on any page because they are not promoted to being a top-level annotation. So in your example, my replies would no longer be visible. I think that would be a pretty easy fix tho as all we need to do is remove the reference to the deleted annotation on all the child annotations.

**Comment by seanh** [comment] 2018-10-16 09:13
> Reassign the group creator to the most active user of the group automatically

I think there might be a concern about automatically making some unfortunate person who didn't ask for it the moderator / admin / "creator" of the group.

I'm also wondering if we should keep a record of who actually created the group, even though that person is no longer the owner / moderator / admin of the group? That would require adding group moderator as a separate role so we can make someone else the moderator while still tracking the original creator. And it would require allowing a group's creator to point to a now-deleted account.

**Comment by hmstepanek** [comment] 2018-10-16 15:18
I agree-that might be a surprise to people. I don't think it's worth adding another feature to a group (aka a moderators list) just to be able to delete a user account tho.

**Comment by ajpeddakotla** [comment] 2018-10-16 16:41
There's a potential solution which I think would address most of the concerns brought up here - 

What if we archived the group? 

If a user asks Hypothesis staff to delete their account, and if they are the group owner of a group with other Hypothesis members, could we delete their account, and archive the group in such a way that 
1. The group owner's annotations are deleted, or hidden
2. Any replies to owners annotations still show
3. Group is archived, and no annotations can be created in archived group
4. New Members cannot be added to archived group
5. current members can still view annotations created in that group
6. Once all members leave the group and/or delete their accounts, we can delete the group from the database, and all annotations associated with that group.

**Comment by hmstepanek** [comment] 2018-10-16 16:50
> What if we archived the group?

AFAIK we don't have a concept of archiving so I'm not sure what that would look like and the time needed to make such a solution would prob be more time than we want to spend. 

The option I'm leaning the most towards here is re-assign the creator to another member manually or set the creator as None if no one wants to take ownership and fix the replies issue @klemay pointed out.

**Comment by lyzadanger** [comment] 2018-10-16 16:53
Looking at @ajpeddakotla 's most recent suggestion, it's hard for me to take my engineer's glasses off and act like a real human user (i.e. my immediate gut reaction is "that is a lot of functionality to build that we don't have"). One thing I'd like to point out is that an implied feature need has emerged (I think) in several user needs over the past several months: the notion of having some sort of archival or "ghost" state for certain resources, most saliently users.

Some services, like GitHub, have consistent representations for users who have deleted their accounts (and the comments, issues, etc. belonging to those users).

If we were able to have some representation of a no-longer-extant user account, it might obviate the need for having the group itself have a different state (app logic could see that a group's creator/owner is a non-user and lock down the ability to create any new annotations in that group, e.g.).

However, this is gonna be a BIG OLD task, and one we need to think through very carefully. So I'm not suggesting it to attack this problem quickly. Just ruminating.

It might be useful to split out a reasonable-for-near-term-approach (one that eases @klemay 's pain and makes dealing with this situation even _possible_) versus some overall UX and data questions this raises.

Interested in @dwolfe 's input here, too.

**Comment by hmstepanek** [comment] 2018-10-16 16:56
I agree with @lyzadanger about the need for a longer term solution but as she said, I'm not sure now is the time to tackle that. I think setting the user to None and/or finding a new owner is a nice workable solution within our current system.

**Comment by lyzadanger** [comment] 2018-10-16 17:07
@hmstepanek I'd exercise caution if you decide to take the route of setting a group's `creator` to `None`. Strictly speaking, that relation is nullable, but there are a number of places in the app logic that make decisions based on the creator's value. Need to tread carefully :)

**Comment by hmstepanek** [comment] 2018-10-16 17:08
@lyzadanger  I did look into that and I didn't see any issues with it although it's certainly possible I missed something.

**Comment by hmstepanek** [comment] 2019-01-04 17:36
Decision: Setting the group creator to None is simpler than creating an archive or a ghost user and it also doesn't change existing functionality (ability to create new annotations/see other's annotations). Currently, there is one group (Public) that does not have a creator and there is no way to add more than one moderator to a group (only the creator can moderate). Set group creator to None but enable ability to set a new creator through the admin page so that if the group needs a moderator, one can be supplied.

**Comment by klemay** [comment] 2019-08-01 21:09
Closing in favor of https://github.com/hypothesis/product-backlog/issues/909

**Closed as completed by klemay** 2019-08-01 21:09 UTC
