### ISSUE TITLE
Error message while grading: "Unable to fetch grade: LTI outcome request failed."

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1305] opened 2022-01-27 20:54 UTC
## Bug report form

Reported by user https://app.hubspot.com/contacts/6291320/ticket/755053866/

Instructor at College of Western Idaho reports intermittent but regular error message when grading student annotations:

`Unable to fetch grade: LTI outcome request failed.`

With the following error details:
```
{
	"cause": "None",
	"request": {
		"method": null,
		"url": null
	},
	"response": {
		"status code" : 200, ,
		"reason" : ""
	},
	"validation errors" null
}
```

Course details are:

- College of Western Idaho https://blackboard.cwi.edu
- Happens intermittently for an instructor in their course when they are using the grading bar
- Doesn’t seem to matter if the student selected has a previously entered grade or not
- Sometimes the error will pop up when scrolling to a student on the list (or choosing one from the drop-down)
- Sometimes it will only show up when entering a score
- 21 students in course
- No Blackboard groups used

Note: I am unable to replicate in our Blackboard Saas instance.

### LMS details
Blackboard SaaS RELEASE 3900.30.0-REL.39+97A2BE2

**Comment by mkdir-washington-edu** [comment] 2022-01-31 17:35
Also https://app.hubspot.com/contacts/6291320/ticket/760212330, George Mason U.
![image](https://user-images.githubusercontent.com/22603275/151843963-b5ed1ce5-dbc4-4a55-ad7a-cac9045c9f40.png)
> Attaching my error message. Most students don't get this. Help?

**Comment by mkdir-washington-edu** [comment] 2022-02-02 18:59
Steps to reproduce:
1. As an instructor, create assignment in Blackboard
2. As a student, access assignment
3. As an instructor, drop student from the course
4. As an instructor, open assignment and select student from the grading bar
5. See error

Already set up:
1. In https://aunltd-test.blackboard.com/ultra/courses/_23_1/cl/outline
2. access course "MD test course"
3. Student "classclown" has already been removed from the course
4. As instructor access assignment "BB groups test"
5. Select "class clown" from drop down
![image](https://user-images.githubusercontent.com/22603275/152219489-a9087b3a-bb31-464f-b46c-b592972a77d5.png)


**Important notes**
1. Please contact MD when we solve this bug - the ticket needs to be reopened and the partner contacted.
2. The partner who reported this got the error even for students who were not dropped from the course, but we could only replicate for users who **were** dropped. We weren't sure if maybe the app pre-fetches other students when loading a grade and so was still running into dropped students, or if there's a **second** thing also causing this error.

**Comment by seanh** [comment] 2022-02-03 18:20
Previously: https://github.com/hypothesis/support-legacy/issues/169

**Comment by seanh** [comment] 2022-02-03 18:33
You can see these if you [search for "LTI outcome request failed" in Sentry](https://sentry.io/organizations/hypothesis/issues/?project=259908&query=is%3Aunresolved+%22LTI+outcome+request+failed%22&statsPeriod=14d): 91 events in the last few months.

**Comment by mattdricker** [comment] 2022-12-01 21:55
Same issue seen again at CUNY Lehman, raised in slack https://hypothes-is.slack.com/archives/C2BLQDKHA/p1669930118399169

Adding this to the new support board project for investigation by dev team.

**Comment by marcospri** [comment] 2022-12-02 11:37
For dropped students this makes sense, our grading works like:

- Students submits annotations, we store their name and id
- Student gets deleted from the course. We don't know about it.
- Instructor opens grading bar, we display all the names/ids we seen, including the deleted one. 
Reading the grade fails for deleted students.

Potential solutions:

1. Handle this error with a dialog saying something about dropped students. If we have another problem here then reports would be about "my student has not been dropped" rather than a mysterious grading error.

2. Silently fail and return no grade. Probably not a good idea.

3. In LTI1.3 we could use the roster service to periodically refresh the students and only show those in the grading bar. This would take more work and only work in 1.3 but I reckon is something we want to take advantage (that's an LTI pun btw) at some point.


Note that in LTI1.1 dropping from the course and getting added again probably causes the same issue (a new grade item would be created).

**Comment by marcospri** [comment] 2022-12-08 14:12
Behavior across different LMS:

### D2L

#### 1.3

- Reading the grade of un-enrolled students seems to be indistinguishable from "no grade"
- Writing does fail with a 403 and `'User in requested score is not enrolled in the org unit'`

#### 1.1

- Reading the grade of un-enrolled students seems to be indistinguishable from "no grade"
- Writing new grades succeeds even it it's not possible to read it later :shrug:

**Comment by mkdir-washington-edu** [comment] 2023-01-16 14:58
Another ticket to reply to once this is fixed: https://app.hubspot.com/contacts/6291320/ticket/1374317320

**Comment by mkdir-washington-edu** [comment] 2023-02-02 17:13
@darylhedley from our meeting today, it might be helpful to have the backend team look at this and think of anything else they can add for debugging purposes. Maybe in papertrail?

**Comment by marcospri** [comment] 2023-02-02 18:07
@darylhedley @mkdir-washington-edu for the specific case of students no longer in the course, which I bet is a high proportion of these errors, there's no need to keep debugging it's easy to reproduce.

As I mention above what we need is a decision on how to solve this situation, is an error dialog describing the problem good enough? Do instructors expect to grade students that left the course? Maybe that's somehow possible using the UI but not the API?.

**Comment by mkdir-washington-edu** [comment] 2023-05-18 21:37
https://app.hubspot.com/contacts/6291320/ticket/1631063158

**Comment by marcospri** [comment] 2023-05-23 10:05
Catching "not in course" errors in the backend now since: https://github.com/hypothesis/lms/pull/5333

Need to handle those in the frontend, we don't currently look at error codes there, explained here: https://github.com/hypothesis/lms/pull/5330

**Comment by marcospri** [comment] 2023-06-14 11:22
Deployed caching of LTI A tokens. These are needed for grading request in LTI1.3 and were causing lots of time outs.

Those should not happen anymore/not as often and we should be able to see other grading related issues.

**Comment by marcospri** [comment] 2023-07-25 15:34
Closing this in favor of more focused issues (course finished, student not in course, ...)

Feel free to reopen or ping me with new occurrences.

**Closed as completed by marcospri** 2023-07-25 15:34 UTC
Labels: bug, Backend
