### ISSUE TITLE
Proposal: When the annotations tab is empty and the pagenotes tab is nonempty, focus the latter

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#375] opened 2017-10-30 18:36 UTC
I've fielded two different support requests recently that boil down to this:

![image](https://user-images.githubusercontent.com/46509/32189018-b67d35fc-bd66-11e7-8fad-49af36571998.png)

The message says "There are no annotations" when in fact there are pagenotes. In this case perhaps we can focus the pagenotes tab?

**Comment by dwhly** [comment] 2017-10-31 15:25
YES.  Actually as this was the originally designed functionality (trying to find our original design notes to prove it), this might actually be more appropriate as a bug report?  @ajpeddakotla?

**Comment by judell** [comment] 2018-02-08 03:53
Here's the simplest solution I can find:

https://github.com/judell/client/commit/0fc4efdbe824046b6ec941423c5347e9f4b2fc2f

Having some solution matters particularly when importing page-level comments, as from PubMedCommons. When a corpus like that is unannotated except for page notes,  you'd like those notes to show on page load.

And you'd like to not see `There are no annotations in this group ` because you landed on the default tab which happens to be empty.

**Comment by ajpeddakotla** [comment] 2018-02-08 18:01
### Problem: 
When there aren't any annotations, but there are page notes, the user is shown the annotations tab. They cannot see that there are page notes, unless they click over to the page notes.  

### Current Behavior: 
User sees this screen even if there are page notes on that page. 
<img width="292" alt="screen shot 2018-02-08 at 11 59 52 am" src="https://user-images.githubusercontent.com/7463523/35989742-9a38239c-0cc7-11e8-8d5f-89584acc18a4.png">

### Expected Behavior: 
If there are page notes, but no annotations, focus the user on the pages notes tab.

**Comment by hmstepanek** [comment] 2018-02-22 05:06
@ajpeddakotla @judell I just want to clarify here...(I think I was a little confused by the screen shot Arti uploaded as it was on the Page notes tab and there were no page notes.)This is what I'm seeing currently and the issue is simply as Arti stated; you would like to change the default behavior when the side bar expands to open to the page notes tab rather than Annotations-correct?

Currently sidebar opens to always:
![image](https://user-images.githubusercontent.com/30059933/36521353-3f9874b2-174b-11e8-9666-462f6dcfbb2e.png)

Would like sidebar to open to (when there are only page notes):
![image](https://user-images.githubusercontent.com/30059933/36521369-58a21ec2-174b-11e8-9056-20ecee8ff315.png)

**Comment by dwhly** [comment] 2018-02-22 15:01
> you would like to change the default behavior when the side bar expands to open to the page notes tab rather than Annotations-correct?

Only when the annotations tab is empty and the page notes tab is not.  Otherwise as is.

**Comment by judell** [comment] 2018-02-22 18:07
@hmstepanek an example of a working solution is https://github.com/judell/client/commit/0fc4efdbe824046b6ec941423c5347e9f4b2fc2f. Not saying it's THE way to do it, but it seems simple and well-localized. That's a place where the loaded annotations are available for counting and classification, and where annotationUI.selectTab is available to make the switch if needed.

**Comment by ajpeddakotla** [comment] 2018-03-19 11:35
Closing as issue is completed.

**Closed as completed by ajpeddakotla** 2018-03-19 11:35 UTC
