### ISSUE TITLE
Changing sections_enabled status via the LMS admin portal does not affect whether section groups are available in the canvas course

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1304] opened 2022-01-22 13:55 UTC
### Steps to reproduce
1. Create a Canvas assignment in a course that uses a consumer key with sections_enabled=true
2. Verify multiple groups show up matching Canvas sections
3. Use the LMS admin portal to disable Sections for that consumer key
4. Refresh assignment and see if available group has changed

I ended up replicating this with assignment https://hypothesis.instructure.com/courses/276/assignments/2697. There are three prod installs in that course, but I turned Sections off for all three. I did this as part of this Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1642856935326800.

### Expected behaviour
In the past turning off Sections via the admin portal has had an immediate affect in the Canvas course.

### Actual behaviour
AFAICT, nothing.

**Comment by seanh** [comment] 2022-01-24 10:19
> Changing `sections_enabled` status via the LMS admin portal does not affect whether section groups are available in the canvas course

I think this may be the intended behaviour: when you disable the `sections_enabled` feature flag for an application instance that just means that the application instance won't have the sections feature **for any new courses** that start after `sections_enabled` was turned off. Any pre-existing courses will still use sections.

The reason is because users might have created annotations in the section groups, and we wouldn't want them to lose access to those annotations by disabling sections.

New course = any course that did not exist or did not have any Hypothesis assignments yet when `sections_enabled` was turned off.

Old course = any course where a Hypothesis assignment had already been created and launched before `sections_enabled` was turned off.

> In the past turning off Sections via the admin portal has had an immediate affect in the Canvas course.

I don't think it did.

I think sections should probably work the same as groups does: the teacher can toggle sections on or off on a per-assignment basis, and an admin turning the `sections_enabled` flag on or off has an immediate effect on all courses and determines whether the sections option appears when creating/editing assignments. This is a much better and simpler solution. But it's not how sections works currently

**Comment by chrisshaw** [comment] 2022-01-26 02:30
**Issue was linked to Harvestr Discovery:**  [Fix how canvas sections works](https://app.harvestr.io/components/0/list/LAoRP9S--)

**Comment by chrisshaw** [comment] 2022-02-04 15:48
This is as expected and we have better solutions, so we'll close this issue.

**Closed as completed by chrisshaw** 2022-02-04 15:48 UTC
Labels: bug
