### ISSUE TITLE
Does YouTube caption download API work for public YouTube videos?

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1548] opened 2024-07-29 19:01 UTC

**Comment by robertknight** [comment] 2024-08-01 10:26
No. The captions API cannot be used to download captions of public videos according to various posts on the internet and our own tests. It can only be used to download videos where you are the owner.

References:
- https://issuetracker.google.com/issues/241669016 ("Hi, this is working as intended, unless you are the owner of the said video. Unauthenticated users are not allowed to download captions. Thank you.")
- https://medium.com/@cafraser/how-to-download-public-youtube-captions-in-xml-b4041a0f9352
- https://stackoverflow.com/questions/30653865/downloading-captions-always-returns-a-403
- Thread discussing our internal experiments: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1689277129121979

**Comment by robertknight** [comment] 2024-08-01 12:14
Script to reproduce the behavior described in the blog posts: https://gist.github.com/robertknight/b1216e87d4831fccaf7a03a01421d167.

If configured with a video ID that you own, this script fetches the first available captions file and prints it. Otherwise it will successfully list the captions, but fail with a 403 when attempting to download them.

In the process of testing this I encountered an issue where Google's browser-based API Explorer that is built into the YouTube API documentation would fail with a 404 response when attempting to download the transcript.

**Comment by dwhly** [comment] 2024-08-01 15:41
> In the process of testing this I encountered an issue where Google's browser-based API Explorer that is built into the YouTube API documentation would fail with a 404 response when attempting to download the transcript.

Is this because its google and it knows what you're trying to do?

**Comment by robertknight** [comment] 2024-08-02 10:56
I don't know what the issue is in API explorer, but it isn't important.

I'm closing the issue as the question has been resolved.

**Closed as completed by robertknight** 2024-08-02 10:56 UTC
