### ISSUE TITLE
Add organization icons into groups menu

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#502] opened 2018-02-27 15:47 UTC
Introducing the organization icons next to the groups is an improvement over what we currently have in the current version of https://biopub.hypothes.is/ and takes us one step closer to the target revised groups control.

![screen shot 2018-02-27 at 15 49 34](https://user-images.githubusercontent.com/5212631/36738564-b2646ea4-1bd5-11e8-83fe-a0f10465cf2f.png)

**Notes:** 

- We are retaining the 'View groups link' for this iteration.
- The CTA has been updated from '+ New group' > '+ New private group' as this is a better description for the corresponding user action.
- We are losing the world and private groups icons in the groups control menu.
- The simplified top bar is out of scope for this card.

Note: The new design is an interim to get us from the current implementation shown in https://biopub.hypothes.is/

**Biopub group control currently in prod:**

![screen shot 2018-02-27 at 15 46 06](https://user-images.githubusercontent.com/5212631/36738350-3669d1ae-1bd5-11e8-80a9-80ddcba217f6.png)

to the completed working design of the new groups control shown below.

**Target group control:**

![screen shot 2018-02-27 at 15 47 50](https://user-images.githubusercontent.com/5212631/36738452-70225d12-1bd5-11e8-8c7d-ae1c529698af.png)

### See also

* [Organizations spike](https://github.com/hypothesis/product-backlog/issues/515)

**Comment by seanh** [comment] 2018-02-27 15:50
Note that I previously created an issue for adding publisher icons into the groups menu - https://github.com/hypothesis/product-backlog/issues/419 - I've closed that issue in favour of this one

**Comment by seanh** [comment] 2018-02-27 15:54
Note that in Dawa's mockup all of the Biopub open and restricted groups are sorted together in the menu, and the Biopub icon is only shown next to the _first_ Biopub group. Similar for the Hypothesis groups. Developers may have to figure out an intermediate way to implement that given that we don't have publishers / organizations in the model yet.

**Comment by seanh** [comment] 2018-02-27 15:58
I think this is a great design improvement. It's a small (ish) iterative step from what's currently on production, small enough that we can probably handle it as a single increment (pending discussion with other devs), and it makes a huge improvement to the product. Low effort and high value.

I think it makes the ownership of the groups (owned by Biopub vs owned by Hypothesis) clear, which is not clear at all from the current UI on production. Previously all groups were owned by Hypothesis but now that we've added open groups we have groups owned by Biopub (or whoever) but have so far failed to distinguish that at all in the UI.

Also I just think that removing the ugly world and private icons, and not repeating the same icons over and over again next to groups, makes it look **so** much better.

**Comment by klemay** [comment] 2018-02-27 16:39
From [ticket #2238 in Zendesk](https://hypothesis.zendesk.com/agent/tickets/2238):

> "It’s been working alright on my laptop lately, though it’s been uneven in terms of whether it will let me save my notes to “public” or to the class group I formed. Sometimes, when I use the dropdown it takes me to my Hypothes.is page and sometimes it lets me save annotations to that group. I never know which it will be."

Through talking with the user, I figured out that she was often missing the target for the group she was trying to select, and instead clicking on the "View group activity" link. Interestingly, the user did not realize she was missing the target and instead thought this was a bug in the product!

I did explain to the user that this is not a bug, so no further action is needed on the ticket - just documenting this here in case it is helpful.

**Comment by robertknight** [comment] 2018-02-27 16:41
> I did explain to the user that this is not a bug, so no further action is needed on the ticket - just documenting this here in case it is helpful.

Very helpful 🙂, thanks for the insight.

**Comment by dawachan** [comment] 2018-02-27 16:42
Thanks for sharing Katelyn, this validates the complaint I received at QDR from folks that actively used H and have encountered the exact same problem!

**Comment by seanh** [comment] 2018-02-27 16:49
Wow, great work

**Comment by seanh** [comment] 2018-08-16 10:46
@ajpeddakotla This is shipped right?

**Comment by ajpeddakotla** [comment] 2018-08-16 15:38
yup again... closing

**Closed as completed by ajpeddakotla** 2018-08-16 15:38 UTC
Labels: Design, groups
