### ISSUE TITLE
Confirm that "Canvas is asking users to authorize frequently" is a bug

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1230] opened 2021-09-23 18:48 UTC
### Steps to reproduce
Can't reproduce reliably, but users have been reporting that they are getting Canvas' usual challenge to authorize API usage multiple times a day. I'm able to reproduce this in our Canvas accounts (professor and students), but I can't force it to happen.

I have the [HAR of a session where I was challenged](https://drive.google.com/file/d/1ZXyzt7gsbKByv6K5HBO2fBXIBvx_ohp-/view?usp=sharing), but I doubt it's different than any other expected challenge.

### Expected behaviour
Users are only challenged at most a few times a semester.

### Actual behaviour
Users are challenged multiple times a day.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

Chrome 94
Firefox 92

**Comment by mkdir-washington-edu** [comment] 2021-11-02 16:01
How often has this occurred?
At the beginning of the semester it seemed to occur every few hours. Now it seems to occur one every several days or so, so something on instructure's end may have changed. That probably makes this lower-pri.

Email conversation with Instructor rep:

**Instructure**
> Can you provide some specifics around the scenario you're describing? This isn't something that I have heard of happening from other vendors recently. Having the specific details about which requests you're making and where the process stops working would be extremely helpful.

**Us**
> We've seen, both in our Canvas instance and from multiple partners using Canvas, that users are being asked to Authorize Hypothesis when we call on API endpoints, sometimes multiple times a day. Our working theory is that the auth token is working correctly, but something is going on (on our end or yours) with the refresh token we're storing after receiving it from you all.
>
> Here's the list of API endpoints we call on: https://github.com/hypothesis/lms/wiki/Canvas-API-Endpoints-Used-by-the-Hypothesis-LMS-App. Groups- and Files-related endpoints are only called on periodically. Sections-endpoints are called on every time we open in our instance and for most partners.
>
> One school I worked with said they've seen this behavior this academic year from "2 or 3" LTI tools who also use Canvas Developer Keys, which is why we think it might not be how we're storing the refresh token (which hasn't changed on our end and used to work fine last academic year) but maybe a change in how you all are using it or sending it.
>
> If you need other details or want to set up a time to talk with an actual developer on our team please let me know. I'm happy to facilitate.

**I**
> Thanks for the details. Based on this description, it seems likely this is caused by how Hypothesis handles the OAuth2 workflow for users the application has already obtained a refresh token for. 
>
> "users are being asked to Authorize Hypothesis when we call on API endpoints, sometimes multiple times a day"
>
> In Canvas, a user would only be prompted to authorize an application if they were redirected to `GET <canvas>/login/oauth2/auth`. This step is only required when a user first authorizes an application. For any subsequent authorization, the application only needs to make the server-to-server request: `POST <canvas>/login/oauth2/token` using a stored refresh token. It sounds like Hypothesis may still redirect users to `GET <canvas>/login/oauth2/auth` despite having / using a refresh token for the user.
>
> Does this sound like a plausible explanation based on the information on your side? If you're able to share an example where a user is prompted to reauthenticate multiple times (in the Hypothesis sandbox or otherwise), we should be able to confirm the issue fairly quickly.

**Us**
> I'll put this information in front of our Devs and get back to you. Thank you very much for it! In the meantime, I'm not sure if I need to approve access for your folks to access our instance, but if not you can find an example of this behavior here: https://hypothesis.instructure.com/courses/258/assignments/1484.
>
> As a note, we haven't changed the Sections API endpoints we're requesting, but the platform's behavior has changed. Have there been changes on your end with regards to handling GET requests and refresh tokens?

**I**
> Thanks for the sandbox example, I was able to reproduce the issue a few times. At least from my minimal interactions, it seems more likely to ask for authorization after not launching the Hypothesis tool for a period of time.
>
> I was prompted for authorization once while I had my browser's dev tools open. Compared to a launch where I wasn't prompted to re-authorize, the only difference I noticed is that the request made to to 'lms.hypothes.is/…/via_url' received a 400. Interestingly however, the Bearer token used to make the failed request did match the token returned in the tool launch. I attached a text file showing details of the succesful launch and the subsequent 400. I'm unsure if these are related, but hopefully this information is useful. 

**Us**
> I think you have the description correct.  I think our point is that 1) this is new, 2) this should not be happening, and that 3) other institutional customers have observed this new behavior with other 3rd party tools in Canvas.
>
> Because of the nature of the way authentication happens here, it would take substantial effort for us to try to get additional detail around this issue— and even then would be quite difficult to debug if possible at all.
>
> Can we request that an engineer inspect this — particularly since you can reproduce.  We're happy to pay for the time if for some reason this is an error on our side.

**I**

> Allow me to expand further on my observations from reproducing the issue with a more Canvas-centric point of view. 
> 
> Having previously granted OAuth2 access to the Hypothesis application, I launched the provided example assignment at 2021-10-06T19:29Z, and was prompted to authorize again. It is worth noting that the prompt wasn't from Canvas, but was displayed in the Hypothesis UI with a link to the Canvas authorization page.
> 
> Without reauthorizing, I opened the same assignment in a new tab. This time the Hypothesis application launches successfully, without prompting for re-authorization.
> 
> So with nothing changing on the Canvas-side that affects Hypothesis' ability to authorize to my account, in my second tool launch, Hypothesis does not produce the re-authorization prompt. In my assessment, this is a strong indicator that the issue likely doesn't relate directly to Canvas' OAuth2 workflow.
> 
> I also took a look at Canvas logs for hypothesis.instructure.com during this time frame, and compared my access to requests coming form Hypothesis:
>  
> 1. [Me, Canvas UI]
> 2021-10-06T19:29:21.727946+00:00 
> GET /courses/258/assignments/1484 (200)
> 
> - Note: this was the first time I had accessed a Hypothesis assignment this day
> 
> 2. [Hypothesis]
> 2021-10-06T19:29:31.777717+00:00
> GET /api/v1/files/796/public_url **(401)**
> 
> 3. [Hypothesis]
> 2021-10-06T19:29:31.816756+00:00
> GET /api/v1/group_categories/135/groups?per_page=1000 **(401)**
> 
> - Requests 2 & 3 were made without first retrieving an access token from Canvas 
> 
> 4. [Hypothesis]
> 2021-10-06T19:29:31.886303+00:00
> POST /login/oauth2/token (200)
> 
> 5. [Hypothesis]
> 2021-10-06T19:29:31.930561+00:00
> POST /login/oauth2/token (200)
> 
> - I was able to confirm both of these request were retrieving access tokens for my account
> - However, getting a new token in request 5 would have invalidated the token returned in request 4. This potentially could explain why request 6 also failed.
> 
> 6. [Hypothesis]
> 2021-10-06T19:29:31.983964+00:00
> GET /api/v1/files/796/public_url **(401)**
> 
> 7. [Hypothesis]
> 2021-10-06T19:29:32.149057+00:00
> GET /api/v1/group_categories/135/groups?per_page=1000 (200)
> 
> 8. [Me, Canvas UI]
> 2021-10-06T19:30:11.774975+00:00
> GET /courses/258/assignments/1484 (200)
> 
> - I reload the assignment in a new tab, this time without a re-authorization prompt from Hypothesis
> - All subsequent requests Hypothesis makes to the Canvas API succeed
> 
> 9. [Hypothesis]
> 2021-10-06T19:30:12.545537+00:00
> GET /api/v1/group_categories/135/groups?per_page=1000 (200)
> 
> 10. [Hypothesis]
> 2021-10-06T19:30:12.557026+00:00
> GET /api/v1/files/796/public_url (200)
> 
> 11. [Hypothesis]
> 2021-10-06T19:30:13.244766+00:00    
> GET /api/v1/files/796/public_url (200)
> 
> 12. [Hypothesis]
> 2021-10-06T19:30:14.295374+00:00
> GET /api/v1/group_categories/135/groups?per_page=1000 (200)
> 
> Reading through these logs, my primary suspicion is around either Hypothesis making requests to Canvas prior to retrieving a valid access token, or Hypothesis retrieving access tokens for the same user in close succession. 
> 
> I should also share that similar issues around OAuth2 have not been reported by any vendors recently. We've also been unable to find any recent changes that we would expect to impact behavior this way.
> 
> If you'd like, I'd be happy to schedule a call with your engineering team and attempt to walk through the issue live. Otherwise we can refer you to Unicon for consulting hours.

**Comment by seanh** [comment] 2022-02-08 18:10
# How to trigger a refresh token request in dev

Normally our app will automatically do a refresh token request with Canvas the next time the user launches an assignment after their Canvas access token has expired. This makes it inconvenient to test refresh requests because you'd have to wait for your access token to expire (which takes one hour, looks like).

You can force a refresh request to happen by breaking your access token. This will break all the access tokens in your DB:

```
$ tox -qe dockercompose -- exec postgres psql -U postgres -c "UPDATE oauth2_token SET access_token = 'foo';"
```

If you now launch an assignment it should launch successfully without asking you to authorize because it will have automatically refreshed the token. You can query your DB to verify that there's a new non-foo token in there:

```
$ tox -qe dockercompose -- exec postgres psql -U postgres -c "SELECT access_token FROM oauth2_token;"
                             access_token                              
-----------------------------------------------------------------------
 9382~lJe***H6s
(1 row)
```

**Comment by seanh** [comment] 2022-02-08 18:16
# How to have multiple web workers in dev

The sequence described by the Instructure rep above won't happen in dev because the app only has one web worker in dev so it'll only send one request to Canvas at a time. In production however we do have more than one worker. You can make dev have multiple web workers by making this change:

```diff
diff --git a/conf/supervisord-dev.conf b/conf/supervisord-dev.conf
index d2dcd513..1d64fafd 100644
--- a/conf/supervisord-dev.conf
+++ b/conf/supervisord-dev.conf
@@ -3,7 +3,7 @@ nodaemon = true
 silent = true
 
 [program:web]
-command=gunicorn --paste conf/development.ini
+command=gunicorn --paste conf/development.ini --workers 4
 stdout_events_enabled=true
 stderr_events_enabled=true
 stopsignal = KILL
```

When you run `make dev` you should then see the `web` process starting multiple workers:

```
$ make dev
web (stderr)         | [2022-02-08 18:14:40 +0000] [890364] [INFO] Starting gunicorn 20.1.0
web (stderr)         | [2022-02-08 18:14:40 +0000] [890364] [INFO] Listening at: http://0.0.0.0:8001 (890364)
web (stderr)         | [2022-02-08 18:14:40 +0000] [890364] [INFO] Using worker: sync
web (stderr)         | [2022-02-08 18:14:40 +0000] [890372] [INFO] Booting worker with pid: 890372
web (stderr)         | [2022-02-08 18:14:40 +0000] [890377] [INFO] Booting worker with pid: 890377
web (stderr)         | [2022-02-08 18:14:40 +0000] [890378] [INFO] Booting worker with pid: 890378
web (stderr)         | [2022-02-08 18:14:40 +0000] [890379] [INFO] Booting worker with pid: 890379
```

**Comment by seanh** [comment] 2022-02-08 18:22
# How to reproduce this issue in dev

After changing my development environment to have multiple web workers (as described above) I can reproduce the issue by triggering a refresh token as described above:

1. Change your dev env to have multiple web workers as described above and restart `make dev`

2. Break all the access tokens in your DB so that the next assignment launch will trigger a refresh: `tox -qe dockercompose -- exec postgres psql -U postgres -c "UPDATE oauth2_token SET access_token = 'foo';"`

3. Launch [localhost (make devdata) Canvas Files Assignment](https://hypothesis.instructure.com/courses/125/assignments/875). It may not be 100% reliable but you will see the **Authorize Hypothesis** dialog.

   Not all types of assignment will reproduce the issue. You need an assignment that triggers simultaneous API requests from our frontend. For example a Canvas Files assignment with sections enabled.

4. **Without** clicking the <kbd>Authorize</kbd> button if you look in your DB you'll see that there's already a new access token in there (`tox -qe dockercompose -- exec postgres psql -U postgres -c "SELECT access_token FROM oauth2_token;"`)

5. If you re-launch the assignment without authorizing it'll launch successfully without asking you to authorize

**Comment by seanh** [comment] 2022-02-08 18:22
I have to say the comments above from the Instructure rep were incredibly helpful

**Comment by seanh** [comment] 2022-02-09 14:21
I'm gonna close this issue as I've confirmed that it is a bug. I've opened an LMS issue to get the bug fixed: https://github.com/hypothesis/lms/issues/3667

**Closed as completed by seanh** 2022-02-09 14:21 UTC
Labels: bug, lms, Backend
