### ISSUE TITLE
Activity pages (for the open-groups-for-publishers use case only)

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#422] opened 2018-01-17 12:00 UTC
As a publisher I want to have an activity page for my open group so that people can view all annotations created by the group in one place.

Notes:

* This might actually just work for open groups. I'm not sure.

Out of scope:

- Replies don't show on activity pages yet. Separate issue.

##### Emergency Glossary - Activity Pages

<dl>
  <dt>Activity pages</dt>
  <dd>The pages under
  <a href="https://hypothes.is/search">https://hypothes.is/search</a> have been
  called "activity pages" internally. They are sort of a search page and a recent 
  activity feed in one.</dd>
  
  <dt>Group activity page or just "group page"</dt>
  <dd>Each Hypothesis private group has its own "group activity page" or
"group page", which is basically an activity page but filtered to just that group, and with a sidebar about the group, for example: <a href="https://hypothes.is/groups/YNieDEMG/seans-test-group">https://hypothes.is/groups/YNieDEMG/seans-test-group</a>.</dd>
</dl>

Annotations in the **Public** group also appear on the <https://hypothes.is/search> page, but the **Public** group doesn't have its own group page.

Only private groups support activity pages. Other types of group, such as eLife's "third-party" group, don't appear on activity pages and the groups don't have group pages (yet).

**Replies** to annotations don't appear on activity pages at all (yet).

**Comment by robertknight** [comment] 2018-01-26 15:16
I had a quick look at this today, a few things I encountered in testing while following up a related discussion:

- The Public group, which is an open group in the sense that it has no explicit list of members, does in fact have a URL: https://hypothes.is/groups/__world__/public . I'm not sure if this just happened or was explicitly designed.
- Groups pages are not shown to logged-out users, they get a 404 page. However open groups ought to be visible to anonymous users. Addressed by https://github.com/hypothesis/h/pull/4754
- The sidebar showing group statistics is not visible for groups which do not have explicit membership (eg. Public, but also open groups). We should continue to show the relevant parts of this sidebar in that case (ie. group metadata, "Edit group" page for admin, but not the member list, leave link or invite box).

**Comment by seanh** [comment] 2018-01-30 13:10
Worth noting that the Public group is not literally one of the new (not yet implemented) open groups. The results will likely be the same but we should re-test with open groups when we have them.

**Comment by seanh** [comment] 2018-01-30 13:10
The "N Matching Annotations" text that normally appears at the top of a group page is also missing from the public group:

![screenshot from 2018-01-30 13-08-26](https://user-images.githubusercontent.com/22498/35567959-d7c65f68-05be-11e8-945f-0829f418c2f1.png)

**Comment by seanh** [comment] 2018-01-30 13:14
We probably need to make sure that open groups don't appear in these search filter suggestions (there could be a lot of open groups that could constantly fill up the search suggestions, and no way to get them out of there):

![screenshot from 2018-01-30 13-11-46](https://user-images.githubusercontent.com/22498/35568071-6e17e50e-05bf-11e8-82e7-7fa46d7172d4.png)

**Comment by seanh** [comment] 2018-01-30 13:15
Same for this dropdown:

![screenshot from 2018-01-30 13-14-18](https://user-images.githubusercontent.com/22498/35568100-9228acc6-05bf-11e8-98cb-43429b4c05c0.png)

**Comment by seanh** [comment] 2018-01-31 12:58
Because the sidebar and "N Matching Annotations" text don't show on an open group's page (as noted) if the group has no annotations the page looks exactly the same as if you'd searched for a group that doesn't exist:

![screenshot from 2018-01-31 12-53-52](https://user-images.githubusercontent.com/22498/35624127-f4f6a81e-0685-11e8-9e44-3359dc77def4.png)

**Comment by seanh** [comment] 2018-01-31 13:02
If you search for an open group using the search bar (<kbd>group:Foobar<kbd>Space</kbd><kbd>Enter</kbd></kbd>) it doesn't redirect you, as it would if Foobar were a private group, to `/groups/<PUBID>/foobar?q=`. Instead you find yourself at a **very** similar looking but confusingly different page: `/search?q=group%3AFoobar` (this is not the group's home page and won't contain things like the group's sidebar once it's working).

(P.S. There seems to be a preexisting bug, even with private groups, where <kbd>group:Foobar<kbd>Space</kbd><kbd>Enter</kbd></kbd> does redirect me to the group's page but <kbd>group:Foobar<kbd>Enter</kbd></kbd> does not.)

**Comment by hmstepanek** [comment] 2018-02-03 08:11
> We probably need to make sure that open groups don't appear in these search filter suggestions (there could be a lot of open groups that could constantly fill up the search suggestions, and no way to get them out of there):

@seanh This confuses me because as a user I think I would find it confusing if I were trying to search for/filter by an open group and it wasn't in the list. Are you not supposed to be able to filter annotations by an open group?

**Comment by lyzadanger** [comment] 2018-02-05 17:26
As I mentioned in a call, the ability to show any open groups in the groups menu on activity pages needs to wait for now—we don't have a way to address this yet (and there could be hundreds, thousands, who knows, of open groups). This isn't the ultimate end point for this, but we need to address it separately.

**Comment by hmstepanek** [comment] 2018-02-06 07:20
This is when I run the backend after creating an open group. No side bar is present. 
<img width="1169" alt="opengroupsearchpage" src="https://user-images.githubusercontent.com/30059933/35846307-fb8bb590-0aca-11e8-968c-787465cccbce.png">

This is when I run the backend and I search for a group that doesn't exist. (This seems very wrong and like a separate issue/bug.) This behaves the same on prod.
<img width="1186" alt="searchfornonexistantgroup" src="https://user-images.githubusercontent.com/30059933/35846336-18ef0196-0acb-11e8-8be3-3618872b1278.png">

**Comment by hmstepanek** [comment] 2018-02-06 16:22
Open groups don't show up in the drop down.
<img width="1307" alt="opengroupsnotpresentingroupsdropdown" src="https://user-images.githubusercontent.com/30059933/35870593-e91267be-0b16-11e8-9bb7-5199d5a9cfd9.png">

**Comment by lyzadanger** [comment] 2018-02-06 16:24
Regarding

> Open groups don't show up in the drop down

See https://github.com/hypothesis/product-backlog/issues/422#issuecomment-363157059

**Comment by lyzadanger** [comment] 2018-02-06 16:27
It's important to note—so I'll add it here!—that the groups that show up in the drop-down here are not obtained from the API. The activity pages do not make use of the API. This is a pattern for most (all?) web application elements that live in `h` itself (versus client). I think in an ideal future world the views here would make use of the APIs, or at least the same services as the APIs.

Instead, the user's groups visible and acted upon here are a product of the `session` module.

Actually, I'm surprised that open groups _don't_ show up at present, as the user's groups are a concatenation of their private groups and groups returned by the `authority_group` service...that is, all "public groups" (yes, both that service and its method(s) need to be renamed).

**Comment by ajpeddakotla** [comment] 2018-02-06 17:05
After discussing this w/ @hmstepanek @lyzadanger @dawariley here are the agreed upon acceptance criteria for this card: 

Activity pages should show the following when it comes to open groups: 
- [x] # of public annotations made in that group

- [x] Name of the group admins (so that H users know who created and controls that group)

- [x] Share link for group (so that H users can share the group)

- [x] Open Groups won't appear in the groups dropdown (for now)

- [x] H users can search for a group in the search box, and it will return any corresponding groups (using existing search rules - future changes to open group discoverability in search will be handled in another ticket). 

- [x] Open groups should have their own groups landing page (like private groups currently do - i.e. https://hypothes.is/groups/8M8734qW/artis-group)

- [x] Open groups pages are visible to logged out users.

- [x] No join link or leave link on side bar.

**Comment by hmstepanek** [comment] 2018-02-08 01:24
Update:
User is not logged in.
<img width="1277" alt="opengrouplandinguserloggedout" src="https://user-images.githubusercontent.com/30059933/35950226-616fdd7c-0c2a-11e8-9f75-722bea2f2c57.png">
Admin user/group creator is logged in.
<img width="1242" alt="opengrouplandingadminuserloggedin" src="https://user-images.githubusercontent.com/30059933/35950229-6532ba4c-0c2a-11e8-8967-1a9e3dc07296.png">
Unassociated user is logged in.
<img width="1257" alt="opengrouplandingreguserloggedin" src="https://user-images.githubusercontent.com/30059933/35950488-ac090006-0c2b-11e8-90d8-860dfe9fa760.png">

**Comment by dawachan** [comment] 2018-02-09 14:26
After working with Hannah yesterday on the activity page, here's a mockup for the Open Group page. Note: the main changes (compared to private group which is included below for reference)

- The authority/domain name plus logo is featured at the top of the right side bar.
- Instead of a list of members, we have moderators.
- There is no link to 'Leave this group' only 'Edit group'.
- Instead of 'Invite new members' the subtitle becomes 'Share group' with the subtext: 'Sharing the link lets people view this group:'.

![activity page - open group](https://user-images.githubusercontent.com/5212631/36032068-b22e6c9e-0da4-11e8-9ee0-ab3e2335a7a3.png)
![activity page - private group](https://user-images.githubusercontent.com/5212631/36032071-b248b7fc-0da4-11e8-886a-1f78f745272c.png)


In the top search bar, as Sean pointed out adding open groups to the search facet "groups" could potentially lead to many results across multiple domains, but I do think it needs open groups need to be searchable. This is part of a bigger discussion which Hannah and I discussed yesterday and Arti and I will be meeting to discuss.  As a workaround for the purposes of this mockup I've added the facet: "Domain:" to the search field. This will narrow down the scope of search and also allow users to search for groups or annotations within a publisher/partner's domain which will make discoverability and search more useful to our users. Note: I will continue to iterate upon search separately from this card - not scoped/defined yet but I am thinking through the end to end user journey.

**Comment by dawachan** [comment] 2018-02-09 14:27
Note: adding the domain facet is also beyond the scope of this card, but in order for the mockup and UX to make more sense I added it for completeness and as a suggestion/point for future consideration.

**Comment by robertknight** [comment] 2018-02-09 15:36
In the mockup above the group has a custom icon. There are a number of implementation issues around adding this [1] which means that I would suggest making adding the icon a separate task. Is that OK @dawariley?

[1] Off the top of my head we need to think about what format(s) we accept, where the icon is stored and how it gets uploaded.

**Comment by dawachan** [comment] 2018-02-09 17:04
@robertknight Absolutely - adding a custom logo should be a separate task, and agreed about the format, resolution, where and upload mechanism. In the first instance, I would say that until we move towards the self serve model they can email heather or me a logo and we manually check it's in the right format, resize and upload it to where it needs to go - thus limiting the implementation scope of this feature.

**Comment by dawachan** [comment] 2018-02-14 13:23
Design specs to make the sidebar clusters make sense. As we introduce additional activity pages it is important not to carry/propagate inconsistencies forward in the UI. Have discussed/walked @hmstepanek through them.

![activity page - stylesheet](https://user-images.githubusercontent.com/5212631/36206373-08db533e-118a-11e8-9447-9174cb39368f.png)

![comparison_prod with design](https://user-images.githubusercontent.com/5212631/36206383-12cac3ca-118a-11e8-8b40-f51e963b7377.png)

**Comment by dawachan** [comment] 2018-02-14 15:06
@hmstepanek I made a comment in: #424 against the activity page for restricted groups design and I wanted to relay it here: the 'Edit Group' link only appears if you are the admin/creator of the group and you are looking at a group you have edit permissions against, otherwise this link will be hidden.

**Comment by dawachan** [comment] 2018-02-14 18:36
@hmstepanek has confirmed this is the way the 'edit group' link exposed/hidden currently works.

**Comment by dawachan** [comment] 2018-02-19 19:26
@hmstepanek Please see the issue referenced in https://github.com/hypothesis/client/issues/644 - show actual date vs month, year. 

Instead of February, 2018 becomes: January 3, 2018.

n.b. This assumes that we are storing the date stamp in addition to month + year.
Also we might want to factor in regional differences e.g.

UK date format: 3 January, 2018
US date format: January, 3, 2018

Let's follow up on this @hmstepanek tomorrow!

**Comment by dawachan** [comment] 2018-02-19 19:29
Also since we don't yet have a truly responsive web implementation, the spacing on mobile increases significantly with the new spacing/positioning of elements for the web specs. This might cause an issue on a smaller device so let's follow up tomorrow @hmstepanek on this as well.

**Comment by ajpeddakotla** [comment] 2018-03-05 15:44
Closing this as it is completed.

**Closed as completed by ajpeddakotla** 2018-03-05 15:44 UTC
Labels: Design, groups
