### ISSUE TITLE
Move the group leave endpoint POST /groups/:id/leave into the API

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#229] opened 2017-03-20 15:20 UTC
It should move to something like `POST /groups/:id/leave` (exact details to be decided). We will have to continue to support the old URL as well until old versions of the client are no longer in use (Rob says for one week b/c it's an undocumented API used only by the client).

Also add it to the JSON API descriptor at [hypothes.is/api](https://hypothes.is/api/).

After this has been added to the descriptor the client should read it from the descriptor, separate ticket for that: https://github.com/hypothesis/product-backlog/issues/230

**Comment by robertknight** [comment] 2017-08-07 14:59
Yes it @seanh, thanks for flagging this up.

**Comment by dhwthompson** [comment] 2017-08-08 12:53
Closing as a duplicate of #157.

**Closed by dhwthompson** 2017-08-08 12:53 UTC
Labels: API, h, OAuth
