### ISSUE TITLE
Mobile Cursor Jumps to Bottom of Page

### ISSUE THREAD

**Issue by jaredgonzales** [hypothesis/product-backlog#878] opened 2018-11-15 01:08 UTC
### Steps to reproduce
1. Open any page/document/link with H on mobile (android)
2. Select large groupings of text quickly, more than two lines

### Expected behaviour
Tell us what should happen.
     1. Selects large groups of text quickly like normal keyboard/selections. Multiple lines of text should be selected for highlighting or annotations.
### Actual behaviour
Tell us what happens instead.
     1. Selection bounces to the bottom of the page. Ends up selecting entire page.
### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.
      1. Chrome browser on Samsung Galaxy S7 Edge with Android 8.0.0 

### Additional details
      1. I can select text anywhere else and it selects fine with the default selection tool/keyboard but is not using H. However, when I open annotations with H my selections get very jumpy. I have to wait one whole second before being able to select the next line. This leads to 5 whole seconds of selecting five lines of text or a whole paragraph, but it often messes it up if my finger goes slightly too far down to the next line. This becomes annoying when selecting multiple lines at once and it jumps to the bottom and I have to scroll back up and try again. I would like to be able to select blocks of text on multiple lines without it jumping to the bottom of a page. For reference, I use outline.com with H integrated most of the time, but it occurs on any site that I use H on. Not related to #857.

### Add tags - did you add labels? 
If this a customer requested feature, make sure to add that label. 
Mobile, Cursor

**Comment by klemay** [comment] 2019-07-09 20:23
We received another report of this today, from someone using Brave from Android ([See Zendesk ticket](https://hypothesis.zendesk.com/agent/tickets/5430
)).

**Comment by mkdir-washington-edu** [comment] 2019-12-12 21:43
I believe this is the same issue: https://hypothesis.zendesk.com/agent/tickets/7418

If you follow this through to the video, note that in addition to the Hypothesis adder, there's another annotating popup and a magnifier running. The magnifier moves, which to me means it might be following the cursor.

**Comment by KalanaPerera** [comment] 2019-12-13 01:59
Having Same issue, +1

**Comment by mkdir-washington-edu** [comment] 2019-12-27 13:49
https://hypothesis.zendesk.com/agent/tickets/5554
https://hypothesis.zendesk.com/agent/tickets/7477

**Comment by KalanaPerera** [comment] 2020-01-09 06:49
is there any update on this?

**Comment by klemay** [comment] 2020-01-09 15:30
Hi @KalanaPerera - we're in the final stretch of a major overhaul of our frontend, including a bunch of mobile-friendly changes. We're hoping that this will resolve the issue for Android users, and will look further into this if it doesn't. I've added this issue to our bug backlog to make sure it doesn't get forgotten.

**Comment by KalanaPerera** [comment] 2020-01-10 06:25
Hi, @klemay Thank you for the detailed message. Is there any planned release date? 

And I am interested in contributing yo this application :)

**Comment by klemay** [comment] 2020-01-10 17:23
@KalanaPerera we release continuously, so incremental changes will be released over the next few weeks. 

Where/how would you be interested in contributing to Hypothesis? As you know, our code is all here on Github and our development docs are here: https://h.readthedocs.io/en/latest/

We also have a public slack: https://join.slack.com/t/hypothesis-open/shared_invite/enQtMzAxMTEwODAwMTgxLWEwZWYyYjIwYjU3NmFmNDZkOTlmZTcwNzAzMTY5MjFkMTFlZGFiM2Y1NmQxMzQ3NzY4ZjhlMjE5ZjRjNmRlZjg

**Comment by mkdir-washington-edu** [comment] 2020-05-25 14:05
This user has provided better steps for reproducing the error: https://hypothesis.zendesk.com/agent/tickets/10230

The uncontrolled scrolling seems to happen when the text selection passes over the Hypothesis Adder.

**Comment by klemay** [comment] 2020-05-27 16:49
@mkdir-washington-edu is it possible to copy and paste the steps for repro-ing + any screenshots provided without giving away any of the user's personal info?

**Comment by mkdir-washington-edu** [comment] 2020-06-04 19:35
@klemay Sure! I don't think the user's info is in any of this. Here's their explanation:

> The bigger issue is the one you can see in the video i attached: in the majority of websites (very few has not this issue) if you, while highlighting, pass over the hypotes.is popup, the page will automatically scroll down until the bottom. This make the Via service almost unusable.
> I use Yandex, but i tried also on Brave and Chrome meeting the same problem.
>
> The second issue is the one you can see in the picture attached. Sometimes (very rarely) the hypotes.is popup is covered from the system popup

Screenshot:
![screen](https://user-images.githubusercontent.com/22603275/83802123-35602080-a678-11ea-9b99-4339b3dd05c7.jpg)

Can't upload the vid to GitHub, find it here: https://drive.google.com/file/d/13RPufs9ZrDXRZ2AAEEx4zDPVyZgUXqEK/view?usp=sharing


---

In the video, you can see the issue happens when the user's highlight travels over the Hypothesis Adder. At that point the page "jumps" to the bottom.

**Comment by williamgunn** [comment] 2020-10-01 20:50
Same issue here & it's probably the biggest barrier to me making H part of my workflow.

**Comment by dwhly** [comment] 2020-10-01 21:01
@williamgunn iOS or Android?  Can you reliably repro?  Possible screencapture?  We're having trouble w/ repro internally here.  Would be helpful to have a closer friend who can demo this.

**Comment by williamgunn** [comment] 2020-10-02 00:23
> @williamgunn iOS or Android? Can you reliably repro? Possible screencapture? We're having trouble w/ repro internally here. Would be helpful to have a closer friend who can demo this.

Sure, let me see what I can do.

**Comment by williamgunn** [comment] 2020-10-02 16:49
> @williamgunn iOS or Android? Can you reliably repro? Possible screencapture? We're having trouble w/ repro internally here. Would be helpful to have a closer friend who can demo this.

See screen recording here. https://www.dropbox.com/s/ah405hyyy8mfbm1/1601598649-video.mp4?dl=0

Android 10
Brave Browser
Versions & build numbers in screenshot.
![Screenshot_20201001-174425](https://user-images.githubusercontent.com/746636/94876940-f2d40800-040d-11eb-90a9-794892d2b09e.png)

Happy to jump on Zoom & share my screen or let one of the devs take control for a bit to try things. I'd really like to help!

**Comment by klemay** [comment] 2020-10-02 18:34
Thank you @williamgunn, especially for the offer to get on a call with our devs! This is near the top of our "bugs to fix" queue, with just 1 or 2 small things ahead of this. I'll be in touch if we need further help with repro, and/or when this is fixed!

**Comment by williamgunn** [comment] 2020-10-03 16:06
I have some good news on a potential workaround! This bug does not appear to happen in Firefox Beta for Android, at least not yet. 🙂

**Comment by williamgunn** [comment] 2020-10-07 15:28
> I have some good news on a potential workaround! This bug does not appear to happen in Firefox Beta for Android, at least not yet. 🙂

Hmm... Seeing inconsistent behavior on sites using via proxy with mobile Firefox, so this isn't a workaround after all. I'll file a new issue for these, if there's not one already.

**Comment by klemay** [comment] 2020-10-07 15:36
@williamgunn we've just pulled this issue into our sprint. if you want to email me (katelyn@hypothes.is) re: what you're seeing I have a creepily detailed memory of our open issues and may be able to save you some effort in searching

**Comment by LMS007** [comment] 2020-10-09 23:38
Quick update. This happens when you select text quicky, and inadvertently highlight text in the adder itself [Annotate, "Highlight | Show [#]". Because the adder is at the bottom of the dom (last node in body) it selects all the text from where you started the range to the end of the page and causes the page to scroll all the way to the bottom. I also found it happens more often (maybe?) when transitioning from text nodes that span different common ancestors.  You can also observe a flickering condition if you lower the buffer delay  for `selectionEvents` in selections.js (0ms for example). While the adder is its own shadow dom, it does not appear to matter when selecting text nodes.

**Comment by robertknight** [comment] 2020-10-12 12:38
A partial solution for this has been implemented (see https://github.com/hypothesis/client/pull/2625). The "Annotate"/"Highlight" toolbar has been modified so that the browser will no longer try to select text in it, which typically results in the rest of the page being selected as well. The toolbar can still get in the way of making a multi-line selection to varying degrees. We're looking into further improvements. Notes on that here: https://github.com/hypothesis/client/pull/2625#issuecomment-707085942

**Comment by LMS007** [comment] 2020-10-12 15:44
Closing this out now as the primary issue has been fixed. Opened a related UX issue
https://github.com/hypothesis/client/issues/2626

**Comment by LMS007** [comment] 2020-10-12 15:45
Closing this out now as the primary issue is resolved. Opened a related UX issue for further improvements.
https://github.com/hypothesis/client/issues/2626

**Closed as completed by LMS007** 2020-10-12 15:45 UTC
