### ISSUE TITLE
[client] Accessibility: Announce when I save a reply

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1348] opened 2022-04-28 05:35 UTC
**As a user using assistive technologies like NVDA, JAWS, or VoiceOver, I want to be notified when I save a reply, so I can move on confidently to engage in discussions more quickly.**

A reviewer in an accessibility review considered it a major defect that, upon saving an reply, the user would not know anything actually happened:

> Posted reply but screen reader did not hear any verbal confirmation
> 
> Provide a confirmation message.
> 
> Major

## Related

Related to https://github.com/hypothesis/product-backlog/issues/1347

**Comment by chrisshaw** [comment] 2022-04-28 05:36
**Issue was linked to Harvestr Discovery:**  [Hear announcement when I save a reply](https://app.harvestr.io/components/0/list/F0PyPexGW)

**Comment by lyzadanger** [comment] 2022-04-28 12:07
This is actually a dupe of #1345 — replies are just another kind of annotation.

**Comment by chrisshaw** [comment] 2022-04-29 03:41
My only thought here was whether we want the message to be different for each type of annotation. E.g., "Posted annotation" vs "Posted reply." If so, I wasn't sure if the knowledge of a parent was readily accessible (and so may involve additional feature work).

**Closed as completed** 2022-05-18 12:10 UTC
Labels: accessibility, Added to sprint, product
