### ISSUE TITLE
Show replies on activity pages

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/product-backlog#232] opened 2017-03-21 17:14 UTC

**Comment by klemay** [comment] 2018-01-22 19:36
An issue related to this came in via Zendesk today: https://hypothesis.zendesk.com/agent/tickets/1990

(the user thought replies weren't showing up because she changed the email address associated with her account, but Jeremy explained that this is expected behavior)

**Comment by jeremydean** [comment] 2018-01-22 19:40
I get this email all too often--this one 1/22/18:

> Jeremy,

>A question—I just realized that replies to others' comments aren't included in the summary of a user's annotations. Are there any plans to change that? It'd be nice for students to have more of an incentive to engage in replies.

>Should I add this to GitHub Issues?

>Best,
>Nathan

**Comment by judell** [comment] 2018-01-22 19:47
Related to https://github.com/hypothesis/product-backlog/issues/378, these should probably coalesce.

**Comment by klemay** [comment] 2018-01-22 21:49
User-submitted issue: https://github.com/hypothesis/h/issues/4747

**Comment by klemay** [comment] 2018-01-31 16:02
Another request from zendesk: https://hypothesis.zendesk.com/agent/tickets/2137

**Comment by klemay** [comment] 2018-02-01 22:39
Another user requests this: https://hypothesis.zendesk.com/agent/tickets/2145

> There are currently two aspects of working with Hypothes.is that are suboptimal to me... Responding to questions (and other annotations) published by students within our private group (from the Hypothes.is web site)... It is not possible to see whether an annotation already received a reply on the Hypothes.is site.

**Comment by judell** [comment] 2018-03-05 20:45
See also: https://github.com/hypothesis/product-backlog/issues/378

**Comment by klemay** [comment] 2018-03-29 21:23
[From Zendesk](https://hypothesis.zendesk.com/agent/tickets/2336):
> The change that would be most useful to me as an instructor would be for replies on comments to appear under the user's ID. I prefer to grade participation by clicking through to each student's profile and seeing all of their comments there, but replies don't appear on that page.

**Comment by klemay** [comment] 2018-04-04 15:34
Another request: https://hypothesis.zendesk.com/agent/tickets/2379

**Comment by klemay** [comment] 2018-06-19 16:14
Closing in favor of https://github.com/hypothesis/product-backlog/issues/378

**Closed by klemay** 2018-06-19 16:14 UTC
Labels: activity pages, user requested
