### ISSUE TITLE
Allow "link fragments" in the LMS app

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1307] opened 2022-02-01 19:06 UTC
### Problem you are trying to address with this feature
We've had users report that when they use a page with "link fragments" (links to an anchor on the same page, just farther down the page) the LMS app will open that link in a new window as we would for normal links instead of just scrolling the page down like they'd expect.

I don't have a specific URL, but I can try to find one if this needs testing.

### Your solution
Ultimately links that are to the page you're already on shouldn't reload the page in our app, but just enabled navigation on the page itself.

### Add tags - did you add labels? 
If this a customer requested feature, make sure to add that label.

**Comment by robertknight** [comment] 2022-02-01 19:09
Fragment links are supposed to work already ([relevant code](https://github.com/hypothesis/viahtml/blob/35058390e0ca91b0964d8b871ea310378cc95d23/viahtml/templates/banner.html#L88)). If there are cases where they don't scroll the page but open a new tab that's a bug. Can you collect details of pages and links where this happens and add them to the issue.

**Comment by mkdir-washington-edu** [comment] 2022-02-01 19:11
I'll do my best to have the user send me the page they were talking about. Thanks!

**Comment by mkdir-washington-edu** [comment] 2022-02-01 19:39
@robertknight That was quick! Here's an example: https://jeffreycwitt.com/pl339/docs/02-the-medium-is-the-message.html

I put it into this Canvas assignment and can repro the behavior: https://hypothesis.instructure.com/courses/266/assignments/2764

Note that I've clicking the embedded ToC ("Overview", "McLuhan: The Medium is the Message", "Consider the Objections"), **not** the  left-hand menu that actually brings you to other pages.

I can also repro in Via (as you'd expect): https://via.hypothes.is/https://jeffreycwitt.com/pl339/docs/02-the-medium-is-the-message.html

**Comment by robertknight** [comment] 2022-02-02 07:09
I can reproduce the issue with the ToC at the top of the content page. The problem is that DOM APIs monkey-patched by Via are not behaving as they do normally.

There is [some code](https://github.com/hypothesis/viahtml/blob/35058390e0ca91b0964d8b871ea310378cc95d23/viahtml/templates/banner.html#L65) that tries to determine if an anchor link refers to the same URL as the current page, except for the fragment. See comments for why it works this way.

```js
const internalLink = document.createElement('a');

// nb. `href` always returns an absolute URL when read.
internalLink.href = '#';
```

If you run this code in the browser console when visiting https://jeffreycwitt.com/pl339/docs/02-the-medium-is-the-message.html#mcluhan-the-medium-is-the-message, reading `internalLink.href` will return the URL of the current page with `#` at the end - `https://jeffreycwitt.com/pl339/docs/02-the-medium-is-the-message.html#mcluhan-the-medium-is-the-message#`. When viewing the proxied version of the page however it returns `https://jeffreycwitt.com/pl339/docs/#`. The `#` has been treated as a relative path instead of a fragment.

Some alternative ways to get the proxied URL of the current page:

1. The `window._WB_wombat_location` object. `_WB_wombat_location` is a fake version of `window.location` which behaves as if the location is the original page rather than the proxied page. A downside is that this name is not a "public API" of pywb AFAIK, although any future version of pywb will almost certainly have to expose something similar.
2. The existing `proxiedURL` variable which is injected by viahtml. Before relying on this we'd have to check what happens in the event that the page initially requested redirects to some other URL.

**Comment by robertknight** [comment] 2022-02-02 09:35
In testing I found that once the above issue is fixed, there is another issue. When you visit [the page](https://jeffreycwitt.com/pl339/docs/02-the-medium-is-the-message.html) directly, the HTML for the Table of Contents links above the content look like this:

```html
<a href="#mcluhan-the-medium-is-the-message" id="markdown-toc-mcluhan-the-medium-is-the-message">McLuhan: The Medium is the Message</a>
```

When rendered [through Via](https://via.hypothes.is/https://jeffreycwitt.com/pl339/docs/02-the-medium-is-the-message.html), the content looks like this:

```html
<a href="https://jeffreycwitt.com/pl339/docs/02-the-medium-is-the-message.html#mcluhan-the-medium-is-the-message" id="markdown-toc-mcluhan-the-medium-is-the-message">McLuhan: The Medium is the Message</a>
```

If the behavior of Via to open external links in a new tab is disabled, clicking this link navigates the page to the _unproxied_ URL in the viahtml iframe. As a result the Hypothesis client disappears.

As a result, if we just "fix" the client-side link fragment handling to detect these as internal links, then they will still be broken but in a different way.

The ideal behavior here would be that fragment links (ie. `<a href="#some-anchor">...</a>`) are not modified by Via. I don't know whether this rewriting is intentional or not.

**Comment by robertknight** [comment] 2022-02-02 09:40
The same behavior can be observed for fragment links on other pages, eg. https://reactjs.org/docs/react-api.html.

**Comment by robertknight** [comment] 2022-02-02 15:26
See https://github.com/hypothesis/viahtml/issues/297 for a proposal that would fix this.

**Comment by lyzadanger** [comment] 2022-02-02 15:26
If the linked proposal is satisfactory, @chrisshaw , this is ready to go into "Ready" state.

**Comment by robertknight** [comment] 2022-02-17 07:04
Fixed via the merged PRs mentioned in this issue.

**Closed as completed by robertknight** 2022-02-17 07:04 UTC
Labels: bug, lms, Added to sprint
