### ISSUE TITLE
Automate client deployment on Jenkins

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#758] opened 2018-08-16 14:24 UTC
**Bring client deployments in line with the rest of our apps** (h, lms, bouncer, and via).

This is a big job (basically involves writing a new client deployment process from scratch) but it is badly needed, and has been needed for a long time. If you need convincing, witness [the team trying to do a client release](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1534425652000100).

Deploying h used to be just as bad as this. A new, Skyliner-inspired deployment process was developed for h (and bouncer, lms and via) that greatly improved the situation, has been successful. This deployment process is deliberately designed to support agile, iterative development and continuous delivery, and to enable all team members to deploy their own changes to production and to feel ownership of how their code works in production, by making deployments fast, automatic, and accessible to the whole team. We need to bring the client in line with the rest of our apps here.

## Done when

- [x] Clicking a single button in Jenkins automatically deploys the client to production (see https://github.com/hypothesis/client/pull/787)
- [x] Deploying the client doesn't involve running any scripts or commands on the developer's local machine, or depend in any way on the developer's local setup - everything happens on Jenkins (see. https://github.com/hypothesis/client/pull/787)
- [x] Merging a client pull request automatically kicks off a Jenkins build that deploys the client to QA (See https://github.com/hypothesis/client/pull/798)
- [x] The client can be immediately tested on QA without any waiting or other tricks (cache-busting, building custom bookmarklets or browser extensions, etc) (See https://github.com/hypothesis/client/pull/798)

## Problem

The current process for releasing a new version of the embedded client (documented in [Doing a Client Release](https://github.com/hypothesis/playbook/blob/master/docs/doing-a-client-release.md)) and the Chrome extension (documented in [Releasing a new version of the extension](https://github.com/hypothesis/playbook/blob/master/docs/chrome-extension.md#releasing-a-new-version-of-the-extension)) is manual, complex, unreliable, and risky. It depends on the local set up of the developer doing the release, many things that are used only to do infrequent client releases need to be present and correct on the developer's machine. Scripts make lots of unsafe assumptions. Many attempts by team members at doing a client release run into problems resulting in complicated, stressful and time-consuming situations for those developers to resolve, and usually requiring multiple team members to be brought in to help resolve the situation. This is costly to developer time and morale and to developers being able to feel ownership of and responsibility for the released client product.

Almost none of our team members feel confident in doing a client release, or feel that they have time to do a client release while trying to deliver sprint aims.

For a most recent example of the problem, see: https://hypothes-is.slack.com/archives/GBN029Q56/p1534419836000100

To get an idea of the degree of complexity involved, some of the things a developer has to do to release the client are:

* Install npm and jq locally
* Set up an npm account for themselves
* Have correctly set up local clones of the client and frontend-toolkit repos (correct meaning matching all the undocumented assumptions that various scripts make)
* Create a GPG key and have it set up locally
* Have git configured to use the right GPG key
* Have the right GPG key added to their GitHub account
* Create a GitHub Personal Access Token with the right settings and have that set up locally
* Follow a 9-step release process and deal with any problems that occur during it
* And _then_ begin the multi-step process of also releasing the Chrome extension

## Solution

We need to bring client deployments in line with the successful approach we use for making deployments of all our other apps practical and accessible to the whole team. Client deployments should work like this:

1. A developer posts a client pull request to github.com/hypothesis/client/pulls

2. The PR is reviewed and approved by another developer

3. The original developer merges the PR

4. Automatically, without any human action, Jenkins deploys the embedded client to https://qa.hypothes.is/embed.js

5. The developer can quickly and easy (within 3 mins, and without any extra steps) test the embedded client on QA.

   Various QA sites that we have can be configured to use the QA version of the embedded client: https://qa.hypothes.is/ (e.g. the /docs/help page), https://qa-via.hypothes.is, https://qa-lms.hypothes.is, https://biopub.hypothes.is/, and a deployed instance of the publisher test site, should all be configured to use the https://qa.hypothes.is/embed.js copy of the client, so the developer can simply use these sites to test the client.

    It's important that this testing not involve needing to login to Cloudflare, use a cache-buster bookmarklet, or other obscure tricks. There shouldn't be any caching of the QA version of the client, as this only introduces the possibility of accidentally testing the wrong (cached) version and not realising it.

6. As with our other apps, the developer then presses a single button in Jenkins to deploy the embedded client to production (https://hypothes.is/embed.js):

   ![screenshot from 2018-08-16 15-00-35](https://user-images.githubusercontent.com/22498/44213319-52ef8d80-a165-11e8-98be-8d8622cb1e18.png)

   The developer can then test the embedded client on production h, production lms app, production Via, on eLife, etc.

   The production client _is_ cached by Cloudflare so we'll need a way of automatically busting that cache.

7. There's one irreducible bit of complexity about the client that does mean that the client deployment process needs to be longer than for our other apps: We release browser extensions containing the client to the Chrome and Firefox stores.

   We should decouple browser extension releases from client releases. The browser extension only needs to be released when client changes that affect the browser extension have been made. All work that we do for publishers, and for education users, for example, uses the embedded client and doesn't require browser extension releases. So we shouldn't allow the browser extensions to get in the way of an improved embedded client deployment process.

   That said, I think it should be possible to mostly or entirely automate browser extension releases as well. Developer clicks another single button in Jenkins, Jenkins builds the extension and uploads it to the stores, nothing required to be set up or run on the developer's machine. (Some clicking of buttons in extension stores UIs may be unavoidable, if APIs don't exist.)

   This final step can certainly be split out into a separate issue.

**Comment by lyzadanger** [comment] 2018-08-16 15:20
> We should decouple browser extension releases from client releases.

+1

**Comment by lyzadanger** [comment] 2018-08-16 15:21
> This final step [releasing browser extension] can certainly be split out into a separate issue.

Certainly, but a situation I'd like to avoid is developers feeling quite comfy with deploying the embedded client but nervy about extension releases, causing the extension to lag too far behind...

**Comment by robertknight** [comment] 2018-09-25 14:00
I removed the "P1" label because Dave and Sheetal were able to successfully do a client release without any input from me last sprint so the problem is not as serious as it might have seemed before.

**Comment by robertknight** [comment] 2018-10-19 13:53
I removed this section from the issue description:

```md
### Remove unnecessary release artefacts 

Our current manual client release process involves creating or updating a few artefacts that we don't have for any of our other apps, and don't need. These get in the way of having a fast, reliable and accessible deployment process. We should do away with these:

* The npm package of the client that we publish. I don't believe we use this for anything?
* Git release commits
* Git release tags
* Git commit signing
* GitHub releases (unneeded and often a source of problems)
* The client's changelog file that has to be manually written and committed to git (and also copied to the github releases page and into Slack) before/during each client release. Just use the `#changelog` channel in Slack as for the rest of our apps, and remove the changelog file
* Version numbers conforming to semantic versioning. Just use automated `20180814-gdc24355`-style version numbers as our other apps do, that the developer doing the release doesn't even have to be aware of.
* Posting updates to Slack. Developers are encouraged to update the `#changelog` Slack channel whenever changes to any of our products have been shipped, but this is not part of the deployment process per se.
```

I think Sean was missing some context about why the client release involves the artefacts that it does, so I'll try to explain them here:

- The npm package is used by the browser extension as a way to pull in the current version of the client
- The client uses semantic versions because the Google Chrome and Mozilla Add-ons stores require version numbers to adhere to a numeric format ('X.Y.Z.W') which semver easily maps to. Also as long as we are using npm as a way to distributed sequential client releases, it makes sense to use semver.
- The Git tags exist because I think it is helpful to have tags that correspond to client releases. This makes it easy to see, for example, which client release a particular commit appears in and thus reason about whether it is present in a release associated with an error report.
- GitHub releases are indeed not essential, but I think a helpful resource for third-party developers. We could consider dropping them if it makes things easier for us.
- The changelog is not essential but it does get used by some tools / services (eg. the GitHub releases page). We can automate the creation of the changelog however, at the cost of not always having quite as helpful entries. We could consider dropping this if it makes things easier for us.
- Posting human-friendly descriptions of relevant changes in Slack is a helpful courtesy to non-developers and I intend to leave this step in the documentation, although the instructions will change.

**Comment by robertknight** [comment] 2018-10-19 13:59
We do not currently have any kind of QA / staging release for the embedded client, though we do for the extension. It is possible to solve the main pain point here before introducing that. My plan of action is as follows:

1. Move the release process entirely to Jenkins, without changing any of the artefacts except for the changelog, which can be machine-generated. (**DONE**)
2. Update the documentation for the client release process accordingly (**DONE**)
3. As a separate step, figure out how to set up a QA release for the client. Before that is done, developers can still check out and test master locally as they do now. For the browser extension we _do_ have a QA version.
4. Automate the deployment of a new browser extension QA release after a new client release has been deployed.

**Comment by robertknight** [comment] 2018-10-19 15:31
The first part of this has been resolved by https://github.com/hypothesis/client/pull/787

**Comment by robertknight** [comment] 2018-10-19 15:32
The deployment documentation is updated in https://github.com/hypothesis/playbook/pull/184

**Closed as completed** 2018-11-02 13:35 UTC
Labels: client
