### ISSUE TITLE
Old H logo visible on iMessage unfurl

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1115] opened 2020-06-03 17:30 UTC
### Steps to reproduce
1. Go to iMessage
2. Paste a group link, for instance: https://hypothes.is/groups/igRizgwB/

### Expected behaviour
Group link should unfurl w/ current H logos

### Actual behaviour
Group link unfurls w/ old H logo

### Browser/system information
iMessage, any version

![Screen Shot 2020-06-03 at 10 29 19 AM](https://user-images.githubusercontent.com/1413074/83668643-264c7600-a585-11ea-8aac-fed08c6540a0.png)

**Comment by xolotl** [comment] 2021-06-30 16:49
Not sure how easy this is to address, but it seems like anywhere we see {"property": "og:image", "content": "/assets/images/logo.png"}, the old Hypothesis logo shows up. Could we change to be the current Hypothesis logo?

**Comment by robertknight** [comment] 2021-07-13 09:18
I had a look at how the new logo actually gets displayed in iMessage. If small (eg. 200x200px) it looks blurry. If the resolution is increased it gets cropped in an unfortunate way ([screenshot](https://github.com/hypothesis/h/pull/6783#issuecomment-878919037)). The problem is that the logo is fundamentally a slightly-taller-than-square image whereas `og:image` consumers (eg. Facebook, iMessage) seem to want a landscape logo.

I proposed to use the same `og:image` image that web.hypothes.is uses ([screenshot](https://github.com/hypothesis/h/pull/6783#issuecomment-878919037)), which has a landscape layout and a sufficiently high resolution. Thoughts?

**Comment by lyzadanger** [comment] 2021-07-30 12:50
This should be fixed as of https://github.com/hypothesis/h/issues/6803

**Closed as completed by lyzadanger** 2021-07-30 12:50 UTC
Labels: activity pages, Design
