### ISSUE TITLE
Indicate to screenreader users whether the sidebar is open or closed

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#771] opened 2018-08-29 17:45 UTC
Part of https://github.com/hypothesis/product-backlog/issues/753.

The button that shows or hides the Hypothesis sidebar should make it clear to those using screenreaders whether the sidebar is currently open or closed.

~See the W3C's page: [Using aria-expanded to indicate the state of a collapsible element](https://www.w3.org/WAI/GL/wiki/Using_aria-expanded_to_indicate_the_state_of_a_collapsible_element).~

As discussed below, the initial proposal (aria-open and aria-closed) attributes don't quite work with our sidebar.

The real requirement we're trying meet here is indicating to screenreader users whether the Hypothesis sidebar is open or closed when interacting with the toggle button. Our user story: 

> As a Hypothesis user who uses a screenreader, when the expand/collapse sidebar button is focused, I need to know what that button does and the current state of the sidebar.

**Comment by ajpeddakotla** [comment] 2018-08-31 18:52
| User Engagement | Building Community | Level of Effort |
|---|---|---|
| 2 | 1 | 3 |

**Comment by lyzadanger** [comment] 2019-09-04 18:21
As can happen, something that sounds relatively straightforward has some wrinkles, given that the goal here is to make it possible for users with screenreaders to be able to ascertain whether the sidebar is currently open/available/"visible" or collapsed/unavailable/"hidden".

The `aria-expanded` attribute relies on source ordering (i.e. DOM structure) to work as intended. The element that expands and collapses should immediately follow the control element (e.g. `button` with `aria-expanded` attribute).

Unfortunately, in our case, the `button`/control element is buried in an `li` element several levels deep _inside_ of the element it toggles. It might sound like we have some fudge factor by whipping out the `aria-controls` attribute, which ostensibly could provide "glue" between the control element and the `id` of the toggle element. But it sounds like support for it is dismal (only JAWS supports it, and kind of weirdly because it's a strangely-design attribute—here is an [article by Heydon Pickering about it](https://www.heydonworks.com/article/aria-controls-is-poop) ).

Semantically, the current location of the button/control vis-a-vis the DOM overall is a bit funky. It'd be helpful to see if @robertknight has any overall thoughts on this one...

**Comment by LMS007** [comment] 2019-09-07 23:51
Just looking at the URL

"aria-controls-is-poop"  lol

Maybe we could do a little light DOM restructure here so it sorta makes sense. W3 just recommends a simple div wrapper. https://www.w3schools.com/howto/howto_css_button_group.asp

**Comment by LMS007** [comment] 2019-09-19 01:35
After digging deeper into this.... 

As Lyza points out, given the fact our collapsible annotation section does not follow the toggle button structurally, I think it's impossible for a reader to know which section is collapsed or not. I feel like this spec is incomplete and we need the equivalent of the simple simple `for=""` attr (for example) when using a `<label>` tag to associate the label with the input.

Maybe we can suggest a new `aria-for` attribute. If we had that, this would be a very simple change.  Short of that, I don't think we can restructure our DOM to make this work for the aria spec -- that would be unreasonable given the complexity and functionality of the client sidebar.

**Comment by klemay** [comment] 2019-09-19 15:36
The `aria-expanded` attribute was a suggestion from the IDRC and it may be that we can meet this accessibility need another way. 

So, reframing this issue a bit, the user story is:

> As a Hypothesis user who uses a screenreader, when the expand/collapse sidebar button is focused, I need to know what that button does and the current state of the sidebar. 

Is this helpful?

**Comment by klemay** [comment] 2019-09-24 15:45
@lyzadanger and @LMS007 I've re-titled and re-framed this issue so we can still meet our WCAG requirement. I'll leave the specifics of the approach to you.

**Comment by LMS007** [comment] 2019-09-25 16:03
Sure, I think there may be another way to do this, I'm gonna tinker around with the screen reader and different ways to convey the sidebar is open or closed.

**Comment by robertknight** [comment] 2019-10-15 07:58
I'm afraid I had to revert the change as it broke on pages that did not supply a custom Hypothesis configuration for the client via the `window.hypothesisConfig` method. See https://github.com/hypothesis/client/pull/1435

**Comment by robertknight** [comment] 2019-10-25 15:34
I have merged a change from @LMS007 so that the open/close and highlights visible/hidden buttons in the toolbar are now correctly identifies as toggle buttons and their active/not-active state is correctly indicated. See https://github.com/hypothesis/client/pull/1436.

**Comment by ajpeddakotla** [comment] 2019-11-06 17:26
Closed as this has been completed

**Closed as completed by ajpeddakotla** 2019-11-06 17:26 UTC
Labels: client, accessibility
