### ISSUE TITLE
Highlight across adjacent PDF pages

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1260] opened 2021-12-08 04:09 UTC
**As a general user, I want to highlight across PDF pages, so that I can capture an entire thought in my annotation and avoid the frustration of the tooltip not working.**

For a real example, see the [comment below](https://github.com/hypothesis/product-backlog/issues/1260#issuecomment-988924566).

## Flow

I'm a user in a multi-page PDF with a paragraph that breaks across pages:

- When I highlight a paragraph across pages, the tooltip shows up
- When I hit Annotate to create a new annotation, the displayed anchor text includes the entire highlight across both pages
- The anchored highlight extends to the text on the second page
  - :information_source: _Firefox will actually let you highlight, but the anchor is only on the first page_
<details>
  <summary>Video</summary>

https://user-images.githubusercontent.com/2966918/145147347-1662ca8d-c6f2-4db9-808b-3675aaeacdaa.mp4

</details>

- I refresh the page. When the page loads, my annotation shows up and the anchored highlight is still in the right place

## Notes

- Other paged formats could benefit from the same approach. Think public published word docs, for example.

**Comment by robertknight** [comment] 2021-12-08 08:38
The incorrect behavior here is actually in Firefox. The client doesn't support creating annotations that span multiple pages and anchoring them later. What is happening in Chrome is the expected behavior.

**Comment by chrisshaw** [comment] 2021-12-08 15:39
@robertknight Somehow I just _knew_ that was going to be true :laughing: 

This was reported by an instructor using it in her class. What would it take to support cross-page annotations?

![image](https://user-images.githubusercontent.com/2966918/145237429-73233c33-75d1-4772-82c2-28e3fa8dfb8a.png)

**Comment by robertknight** [comment] 2021-12-08 15:53
> What would it take to support cross-page annotations?

There is a fair amount of work involved. Various aspects of annotation creation and anchoring assume that each annotation refers only to text on a single page.
 
It will probably help to limit the scope to only selection across up to two adjacent pages rather than an arbitrary number of pages.

**Comment by chrisshaw** [comment] 2021-12-15 01:46
> It will probably help to limit the scope to only selection across up to two adjacent pages rather than an arbitrary number of pages.

@robertknight I'm going to convert this into a story for exactly that.

(P.S. these seem awfully separate, but in case it benefits from/fits into the work that needs to be done for #1253, it may be worth having this story in the back of your mind.)

**Comment by mattdricker** [comment] 2022-10-13 19:02
This issue referenced by user: https://app.hubspot.com/contacts/6291320/ticket/1157100967

**Comment by mkdir-washington-edu** [comment] 2022-11-03 18:53
Seems to be the same issue, or a similar issue, to https://github.com/hypothesis/product-backlog/issues/86.

**Comment by lyzadanger** [comment] 2022-11-30 17:36
I'm going to close this as a dupe of https://github.com/hypothesis/product-backlog/issues/86

**Closed as not planned by lyzadanger** 2022-11-30 17:36 UTC
