### ISSUE TITLE
Investigate issue with DOI queries 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#808] opened 2018-09-21 21:52 UTC
Problem: 
A user reported an issue with DOI queries, in that the query via the API wasn't returning results. This is the query the user was trying: https://hypothes.is/api/search?uri=doi:10.16993/bao

After speaking with @hmstepanek, it does appear that something is going with the ability to query for DOIs. This work in this ticket is to investigate what the problem is, and if possible, to resolve it.

**Comment by robertknight** [comment] 2018-09-25 14:12
> A user reported an issue with DOI queries, in that the query via the API wasn't returning results. This is the query the user was trying: https://hypothes.is/api/search?uri=doi:10.16993/bao

Do you have a link to the original report Arti? I tried this query just now and it is returning results.

**Comment by ajpeddakotla** [comment] 2018-09-25 14:45
Yep @robertknight ticket is here: https://hypothesis.zendesk.com/agent/tickets/3106

**Comment by hmstepanek** [comment] 2018-10-10 21:37
A search for associated urls with doi:10.1523/JNEUROSCI.5212-13.2014 reveals :
 - httpx://www.ncbi.nlm.nih.gov/pmc/articles/PMC3996228
 - httpx://www.jneurosci.org/content/34/17/6112
 - httpx://www.jneurosci.org/content/34/17/6112.long
 - httpx://www.jneurosci.org/content/34/17/6112.full

While a search for associated urls with doi:10.16993/bao reveals:
 - httpx://www.stockholmuniversitypress.se/site/books/10.16993/bao/read?loc=007.xhtml

**Comment by ajpeddakotla** [comment] 2018-10-10 21:44
Another letter from the user came in this week: 
```
My colleague Simon (cc'd) is working on the OPERAS project HIRMEOS, and is trying to pull the annotations associated with a DOI from the Hypothes.is API.

Here is the annotated EPUB (rendered via EPUB.js):
https://www.stockholmuniversitypress.se/site/books/10.16993/bao/read/?loc=007.xhtml
...we have embedded the DOI in the HTML according to your documentation:
<meta name="dc:identifier" content="10.16993/bao">

We can run a query for the URL on your API and return a result:
https://hypothes.is/api/search?url=https://www.stockholmuniversitypress.se/site/books/10.16993/bao/read/?loc=007.xhtml

But we actually want to run a query on the DOI on your API - but this returns no result for this publication:
https://hypothes.is/api/search?uri=doi:10.16993/bao

...although it does work for this DOI query:
https://hypothes.is/api/search?uri=doi:10.1523/JNEUROSCI.5212-13.2014```

**Comment by hmstepanek** [comment] 2018-10-10 21:51
Ah so I get the same results back for both of those queries regardless of whether I use doi or the url directly. So, so far I'm unable to reproduce this problem. Very interesting...

**Comment by hmstepanek** [comment] 2018-10-10 22:27
Out of 6 annotations in the db I'm only able to find 3 of them through the api:
I have [db-reference](https://metabase.hypothes.is/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2VfdGFibGUiOjcsImZpbHRlciI6WyJBTkQiLFsiQ09OVEFJTlMiLFsiZmllbGQtaWQiLDQ5XSwiMTAuMTY5OTMvYmFvIl1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUuY29sdW1ucyI6W3sibmFtZSI6ImlkIiwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiY3JlYXRlZCIsImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJkZWxldGVkIiwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiZG9jdW1lbnRfaWQiLCJlbmFibGVkIjp0cnVlfSx7Im5hbWUiOiJleHRyYSIsImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJncm91cGlkIiwiZW5hYmxlZCI6ZmFsc2V9LHsibmFtZSI6InJlZmVyZW5jZXMiLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoic2hhcmVkIiwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoidGFncyIsImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJ0YXJnZXRfc2VsZWN0b3JzIiwiZW5hYmxlZCI6ZmFsc2V9LHsibmFtZSI6InRhcmdldF91cmkiLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoidGFyZ2V0X3VyaV9ub3JtYWxpemVkIiwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsibmFtZSI6InRleHRfcmVuZGVyZWQiLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoidXBkYXRlZCIsImVuYWJsZWQiOnRydWV9LHsibmFtZSI6InVzZXJpZCIsImVuYWJsZWQiOnRydWV9XX19):
 - This is a test page note.
 - This is a test annotation for a longer passage.
 - This is a test annotation.

All these^ annotations share the same document id. This document id is associated with a doi [db-reference](https://metabase.hypothes.is/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2VfdGFibGUiOjEzLCJmaWx0ZXIiOlsiQU5EIixbIj0iLDg1LDQzOTc0OV1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==). Where as the other two document ids are not associated with a doi [db-references](https://metabase.hypothes.is/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2VfdGFibGUiOjEzLCJmaWx0ZXIiOlsiQU5EIixbIj0iLDg1LDQzOTc2Nl1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==). These are technically different urls but the one that was annotated first (https://www.stockholmuniversitypress.se/site/books/10.16993/bao/read/?loc=007.xhtml) has the doi associated with it and the other ones do not.

So taking advantage of the newly added wildcard search if I do something like this; https://hypothes.is/api/search?wildcard_uri=https://www.stockholmuniversitypress.se/site/books/10.16993/bao/read/?*
I can see all 6 annotations which means they are in fact all indexed into elasticsearch.

**Comment by hmstepanek** [comment] 2018-10-10 23:11
@klemay Perhaps I could borrow you for a couple mins tomorrow just to make sure I'm not missing something really obvious here. Maybe have you try running these two requests and make sure you can't reproduce this either. I tried running these as unauthenticated and it still works for me which makes sense since these annotations are public I shouldn't have to be logged in to view them.

**Comment by hmstepanek** [comment] 2018-10-16 00:10
@ajpeddakotla @klemay 
I received a response from Tom stating now the annotations are showing up and that it was no longer an issue. I told him to definitely let us know if he see's this problem again but for right now I think we can close this.

**Closed as completed** 2018-10-16 14:26 UTC
Labels: bug
