### ISSUE TITLE
WEBSITE GDPR: Adding Contractual Consent to Login Form

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#590] opened 2018-04-20 08:58 UTC
### Background

This card is closely related to: #560 adding explicit opt-ins for privacy policy and to being contacted. The proposal is to add contractual language e.g "By logging in you agree to our privacy policy, terms of service and community guidelines" with links to the respective policies to the **Login form**.

_Current login form below:_

![screen shot 2018-04-20 at 08 37 57](https://user-images.githubusercontent.com/5212631/39040039-80890aa8-447e-11e8-90b8-121f3f553140.png)

_Revised login form below:_
![login form](https://user-images.githubusercontent.com/5212631/39043707-03b3a8fa-4486-11e8-87e0-c8c158172dd0.png)

### Justification

GDPR requirements requires us to meet certain standards with respect to data privacy and storage #564 and whilst the opt-in to our privacy policy on the sign up form covers new users, adding contractual acceptance language to the login form helps us to reach existing users.

**A/C**
- [ ] Contractual privacy policy acceptance language added to the login form e.g "By logging in you agree to our privacy policy, terms of service and community guidelines."
- [ ] Storing that existing users have been 'served' the contractual privacy policy acceptance and opt-ed in via contract based acceptance via: https://hypothes.is/login
- [ ] The revised log in form contains an explicit opt-in to product and research communications checkbox - checked by default. covered in #431

**Comment by robertknight** [comment] 2018-04-20 09:58
I personally don't think it makes sense to a marketing opt-in to the login form itself, because they are only really relevant once for each user after we make changes to the privacy policy or introduce the opt-in. Ideally, I would just rely on having a clear "Unsubscribe" link in the footer of any future marketing emails that we send out.

As for the privacy policy, it might not hurt to provide a quiet reminder of the policy somewhere on the login form. However if it turns out that we do need to get explicit acceptance then I would suggest that we make that a step _after_ login so that we don't show it to the same user more than once. Whether or not we need to do that depends on whether any substantial changes end up being necessary. If the changes are minor enough not to require re-approval, could we simply mention them via email?

**Comment by dawachan** [comment] 2018-04-20 10:06
With regards to the marketing opt-in, the issue we have which is detailed in #431 is that we have over 70,000 currently registered users and we aren't able to contact them. Given the percentage of active vs registered users is quite low - it might necessitate that we need to implement a solution to 'mass mail' and asking for permission, since a only a small % of the registered users will actually go through the revised login. That said, it probably makes sense to remove it on these grounds.

**Comment by dawachan** [comment] 2018-04-20 10:09
"Ideally, I would just rely on having a clear "Unsubscribe" link in the footer of any future marketing emails that we send out."  As I understand it, we do have this now, hence obfuscating the need for managing opt-in via a settings menu for example. Although as I understand from @xolotl and @segdeha we are unable to contact our 145k registered users without explicit consent hence the need for #431 even despite revising the privacy policy language.

**Comment by dawachan** [comment] 2018-04-20 10:11
"As for the privacy policy, it might not hurt to provide a quiet reminder of the policy somewhere on the login form." The quiet reminder is included in the language: "By logging in, I agree to the privacy policy, terms of service and community guidelines." TBD. We are not required to get explicit acceptance, the proposal is to gain contractual acceptance at login because it's less of a road block .

**Comment by dwhly** [comment] 2018-04-20 15:22
@robertknight I'm not sure what you mean by: "Whether or not we need to do that depends on whether any substantial changes end up being necessary. If the changes are minor enough not to require re-approval, could we simply mention them via email?"

**Comment by lyzadanger** [comment] 2018-04-20 15:24
> As for the privacy policy, it might not hurt to provide a quiet reminder of the policy somewhere on the login form. However if it turns out that we do need to get explicit acceptance then I would suggest that we make that a step after login so that we don't show it to the same user more than once. 

Chiming in here that if the privacy opt-in needed to be confirmed for existing users, a step _after_ login seems easier (i.e. possible) to implement because we'll have an extant user and we'll be able to check what the last date of their privacy policy acceptance was and if it was never or of a date we deem too early (i.e. if the privacy policy were ever updated and needed re-acceptance) we could intelligently ask for an opt-in at that time. Displaying it on the login form itself would be blanket—it would get displayed to everyone, all the time, as we have know way of knowing "who" the person landing on the login form is.

**Comment by dawachan** [comment] 2018-04-20 15:30
the proposal in this card is to have a **contract based statement** and not an explicit opt-in at login, similar to how the Khan Academy do it. since this creates less of a 'road block'. thanks for the input though @lyzadanger, and yes if there does have to be an explicit opt-in for privacy policy we could move it to a second step.

![screen shot 2018-04-20 at 08 28 02](https://user-images.githubusercontent.com/5212631/39060021-0c665ba0-44b8-11e8-83da-78fd56928a73.png)

**Comment by segdeha** [comment] 2018-04-20 16:03
This is out of scope. We do not need to make changes to our existing login form. Only the account creation form. Closing.

**Closed as completed by segdeha** 2018-04-20 16:03 UTC
Labels: Design
